// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Sean Hodges

/**
 * PMD 85 acoustic transducer synthesis.
 *
 * The speaker hangs off the low nibble of the motherboard 8255's port C, and
 * unlike the one-bit speakers this project already models it has *three* drive
 * lines rather than one:
 *
 * - **PC0** gates a steady ~1kHz tone and **PC1** a steady ~4kHz one. Neither
 *   is generated by software: both are taps off the video raster counter, which
 *   free-runs whether or not anything is listening. Hold either bit and the tone
 *   is simply connected to the transducer.
 * - **PC2** is wired to the transducer directly, so software that flips it can
 *   make any pitch it likes. Held steady at 1 it drives the cone to one end and
 *   holds it there, which silences the machine - the gated tones included, which
 *   is the documented behaviour and the reason the sources below call a constant
 *   PC2 "acoustic signalling off" rather than "speaker on".
 *
 * The three combine as an OR: any source asserting the line drives the cone.
 * That is what makes a constant PC2 override the tone gates, and what makes
 * PC0 and PC1 together sound like neither on its own rather than like a chord.
 *
 * Facts from the PMD 85 Infoserver's keyboard page (which documents port C bit
 * by bit) and schotek.cz's hardware notes ("bit 0 a 1 vybírají tón z čítače
 * refreshe, bit 2 ovládá zvukový výstup natvrdo"). The Monitor agrees: its
 * key click is `IN 0F6h / XRI 02h / OUT 0F6h` - a bare flip of PC1 - and its
 * one sound table, at 0x80F4, is the three bytes `02 10 FF`, meaning "PC1 for
 * sixteen ticks, then stop". That table is what `BEEP` plays.
 *
 * Note this is *not* the bit MAME's `pmd85` driver drives its speaker from; it
 * uses PC2, which would leave both the key click and `BEEP` silent. Its Maťo
 * handler - the same motherboard, a licensed clone - uses PC1 as here.
 */

import { CPU_HZ, CYCLES_PER_FRAME } from './clock';

/** Output rate of the speaker stream; 44100 / 50 = 882 samples per frame. */
export const SPEAKER_SAMPLE_RATE = 44100;

/** Samples emitted per 50Hz frame. */
export const SPEAKER_SAMPLES_PER_FRAME = SPEAKER_SAMPLE_RATE / 50;

/**
 * The two raster-derived tones, in cycles per full square-wave period.
 *
 * The line rate is the 18.432MHz crystal divided by three for the pixel clock
 * and again by the 384 pixel times a 64-byte line costs: exactly 16kHz, which
 * over 320 lines is the machine's 50Hz frame. The gates take that counter's
 * divide-by-four and divide-by-sixteen taps, so the two tones are exactly 4kHz
 * and 1kHz rather than the "~1kHz and ~4kHz" the documentation rounds them to.
 * Expressed here in CPU cycles because that is the clock the machine counts in,
 * and the same crystal feeds both: 2.048MHz / 512 and / 2048.
 */
const TONE_HZ = { pc0: 1000, pc1: 4000 } as const;
const PC0_PERIOD_CYCLES = CPU_HZ / TONE_HZ.pc0;
const PC1_PERIOD_CYCLES = CPU_HZ / TONE_HZ.pc1;

/** Port C bit masks: the two tone gates and the direct drive. */
const PC0_TONE = 0x01;
const PC1_TONE = 0x02;
const PC2_DIRECT = 0x04;

/** Cone deflection for a driven line, below the headroom the host gain adds. */
export const SPEAKER_AMPLITUDE = 0.6;

/** One-pole DC-blocker coefficient; ~0.995 settles in a few ms at 44.1kHz. */
const DC_POLE = 0.995;
/** Below this magnitude the DC blocker has settled, so a silent slice is free. */
const SILENCE_EPS = 1e-4;

/** Shared empty result so a fully-silent slice allocates nothing. */
const EMPTY_AUDIO = new Float32Array(0);

/**
 * The longest run of machine time one {@link Speaker.render} will voice.
 *
 * The host drains once a frame, so anything past a couple of frames means the
 * machine was fast-forwarded rather than run: booting inside `loadProgram`,
 * seeking a tape, the assistant stepping the machine on its own. That time did
 * not happen at playback speed and there is no honest way to voice it, so the
 * backlog is dropped and the cursor resynced - which is also what keeps this
 * buffer bounded, as `EmulatorPane` expects of a machine that emits audio.
 */
const MAX_SLICE_CYCLES = 2 * CYCLES_PER_FRAME;

interface Transition {
  /** Absolute machine cycle at which port C changed. */
  cycle: number;
  /** The new port C low nibble. */
  portC: number;
}

/**
 * Whether the transducer is driven at `cycle`, given the port C nibble held at
 * that moment.
 *
 * The tone phases come from the absolute cycle rather than an offset into the
 * slice, because the raster counter is free-running hardware: gating PC1 on
 * does not start the 4kHz oscillator, it connects one that was already running.
 * Getting this wrong is inaudible in a single beep and obvious across a run of
 * them, which is why the phase is absolute here and not reset with the gate.
 */
function driven(cycle: number, portC: number): boolean {
  if (portC & PC2_DIRECT) return true;
  if (portC & PC0_TONE && cycle % PC0_PERIOD_CYCLES < PC0_PERIOD_CYCLES / 2) {
    return true;
  }
  if (portC & PC1_TONE && cycle % PC1_PERIOD_CYCLES < PC1_PERIOD_CYCLES / 2) {
    return true;
  }
  return false;
}

export class Speaker {
  readonly sampleRate = SPEAKER_SAMPLE_RATE;

  /** Port C's low nibble as last written. */
  private portC = 0;
  /** Port C's value at the start of the slice not yet rendered. */
  private startPortC = 0;
  /** The cycle the next slice starts at. */
  private cursor = 0;
  /** Changes recorded during the pending slice, in cycle order. */
  private transitions: Transition[] = [];
  /** DC-blocker memory, carried across slices so the filter is continuous. */
  private dcPrevIn = 0;
  private dcPrevOut = 0;
  /** Fractional sample owed from the previous slice, so no cycle is lost. */
  private sampleDebt = 0;

  /**
   * Record port C at the machine cycle it was written. Only the three drive
   * bits matter, so a write that moves nothing else - the red LED on PC3, or a
   * keyboard row going out alongside - costs nothing.
   */
  write(cycle: number, portC: number): void {
    const drive = portC & (PC0_TONE | PC1_TONE | PC2_DIRECT);
    if (drive === this.portC) return;
    this.portC = drive;
    this.transitions.push({ cycle, portC: drive });
  }

  /**
   * Render everything between the last call and `nowCycle`, then arm the next
   * slice. A whole 40960-cycle frame yields exactly
   * {@link SPEAKER_SAMPLES_PER_FRAME} samples; a shorter slice - one debugger
   * step - yields proportionally fewer, with the remainder carried rather than
   * dropped so a run of steps does not drift away from real time.
   *
   * Returns an empty array while the machine is silent: no drive bits set, none
   * set during the slice, and the DC blocker settled.
   */
  render(nowCycle: number): Float32Array {
    const elapsed = nowCycle - this.cursor;
    if (elapsed <= 0) return EMPTY_AUDIO;
    if (elapsed > MAX_SLICE_CYCLES) {
      this.transitions = [];
      this.startPortC = this.portC;
      this.cursor = nowCycle;
      this.sampleDebt = 0;
      return EMPTY_AUDIO;
    }

    if (
      this.transitions.length === 0 &&
      this.portC === 0 &&
      this.startPortC === 0 &&
      Math.abs(this.dcPrevOut) < SILENCE_EPS
    ) {
      this.cursor = nowCycle;
      this.sampleDebt = 0;
      this.dcPrevIn = 0;
      this.dcPrevOut = 0;
      return EMPTY_AUDIO;
    }

    const exact = (elapsed * SPEAKER_SAMPLE_RATE) / CPU_HZ + this.sampleDebt;
    const n = Math.floor(exact);
    this.sampleDebt = exact - n;
    if (n <= 0) return EMPTY_AUDIO;

    const out = new Float32Array(n);
    let portC = this.startPortC;
    let ti = 0;
    let prevIn = this.dcPrevIn;
    let prevOut = this.dcPrevOut;
    for (let i = 0; i < n; i++) {
      const cycle = this.cursor + (i * elapsed) / n;
      while (
        ti < this.transitions.length &&
        this.transitions[ti]!.cycle <= cycle
      ) {
        portC = this.transitions[ti]!.portC;
        ti++;
      }
      const x = driven(cycle, portC) ? SPEAKER_AMPLITUDE : 0;
      // y[n] = x[n] - x[n-1] + R*y[n-1]: passes the tone, removes the DC a held
      // line would otherwise leave sitting under it.
      const y = x - prevIn + DC_POLE * prevOut;
      prevIn = x;
      prevOut = y;
      out[i] = y;
    }
    this.dcPrevIn = prevIn;
    this.dcPrevOut = prevOut;
    this.startPortC = this.portC;
    this.transitions = [];
    this.cursor = nowCycle;
    return out;
  }

  reset(cycle = 0): void {
    this.portC = 0;
    this.startPortC = 0;
    this.cursor = cycle;
    this.transitions = [];
    this.dcPrevIn = 0;
    this.dcPrevOut = 0;
    this.sampleDebt = 0;
  }
}
