import type {
  Dialect,
  MachineEmulator,
  TokenizeError,
  TokenizeResult,
} from '../types';
// The CPC 6128 delegates to the CPC 464 dialect (the bbcmaster/zxspectrum128
// pattern): shared Locomotive BASIC language layer (with the 1.1 keyword
// variant), shared src/emulator/cpc/ machine (model '6128' adds the 128K
// RAM banking and the BASIC 1.1 ROM), shared docs page (docsReference 'cpc').
import { cpcCharset } from '../cpc464/charset';
import { cpcLanguageSupport, cpcCompletionSource } from '../cpc464/language';
import { cpc464KeyboardLayout } from '../cpc464/keyboardLayout';
import { cpc464Samples } from '../cpc464/samples';
import { cpc464BuildTargets } from '../cpc464/targets';
import { cpc6128Keywords } from './keywords';
import { cpc6128AiProfile } from './aiProfile';

/**
 * Amstrad CPC 6128 (Locomotive BASIC 1.1) — SCAFFOLDING ONLY.
 *
 * Throwing stubs generated by the `adding-a-target-system` skill; the staged
 * delegation plan lives at docs/contributing/dialect-plans/cpc6128.md.
 * Intentionally NOT registered in src/dialects/registry.ts until the plan's
 * Stage C (which also adds the `fill` share verb — a BASIC 1.1-only keyword —
 * to src/player/routes.ts in the same change).
 */
export const cpc6128: Dialect = {
  id: 'cpc6128',
  name: 'CPC 6128',
  manufacturer: 'Amstrad',
  year: 1985,
  blurb:
    'The CPC with 128K and a built-in disc drive: the same three MODEs up to 640×200, 27 colours and three-channel SOUND, driven by Locomotive BASIC 1.1.',
  docsReference: 'cpc',
  // Set from what the shipped boot configuration reports (PRINT FRE(0)):
  // 42619 while AMSDOS is deferred, 42249 once AMSDOS lands — see the plan's
  // target summary before changing this.
  programRamBytes: 42619,
  fileExtensions: ['.txt', '.bas'],
  keywords: cpc6128Keywords,
  charset: cpcCharset,
  languageSupport: cpcLanguageSupport,
  completionSource: cpcCompletionSource,

  tokenize(_source: string): TokenizeResult {
    throw new Error('cpc6128: not implemented');
  },

  detokenize(_image: Uint8Array): string {
    throw new Error('cpc6128: not implemented');
  },

  lint(_source: string): TokenizeError[] {
    throw new Error('cpc6128: not implemented');
  },

  createEmulator(_opts): MachineEmulator {
    throw new Error('cpc6128: not implemented');
  },

  // Stage C re-themes these rows as vk-theme-cpc6128 (grey 6128 caps).
  keyboardLayout: cpc464KeyboardLayout,

  samples: cpc464Samples,

  buildTargets: cpc464BuildTargets,

  aiProfile: cpc6128AiProfile,
};
