// Escape-code table for the Commodore escapes page. PETSCII is shared
// byte-for-byte across the C64, VIC-20 and PET, so this one table serves all
// three. Seeded from src/dialects/commodore64/petscii.ts (canonical names +
// PETCAT_ALIASES) and graphics.ts ({CBM-x}/{SHIFT-x}) by
// scripts/gen-escape-scaffold.mts, then hand-enriched. Pinned against the
// implementation by escapes/escape-crosscheck.test.ts.
import type { EscapeTableData } from '../types';

export const commodoreEscapes: EscapeTableData = {
  title: 'Commodore PETSCII escape codes',
  machines: ['Commodore 64', 'Commodore VIC-20', 'Commodore PET'],
  categories: [
    {
      id: 'colour',
      label: 'Colours',
      class: 'colour',
    },
    {
      id: 'cursor',
      label: 'Cursor',
      class: 'cursor',
    },
    {
      id: 'editing',
      label: 'Editing',
      class: 'editing',
    },
    {
      id: 'mode',
      label: 'Modes',
      class: 'mode',
    },
    {
      id: 'keys',
      label: 'Function keys',
      class: 'function-keys',
    },
    {
      id: 'control',
      label: 'Control',
      class: 'control',
    },
    {
      // {space} and {shift-space} are two ordinary PETSCII characters that need
      // an escape only because their glyphs cannot be told apart in the editor.
      id: 'character',
      label: 'Characters',
      class: 'literal',
    },
    {
      // The CBM/SHIFT keycap shapes - the same class as the Sinclair and Atom
      // block graphics, though nothing outside the Commodore family draws them.
      id: 'key-graphics',
      label: 'Key graphics',
      class: 'block-graphics',
    },
    {
      id: 'raw',
      label: 'Raw bytes',
      class: 'raw-byte',
    },
  ],
  entries: [
    {
      escape: '{white}',
      bytes: '0x05',
      category: 'colour',
      description: 'Text colour white (CHR$ 5).',
      aliases: ['{wht}'],
      example: {
        source: '{white}',
        bytes: [5],
      },
      codes: [5],
    },
    {
      escape: '{red}',
      bytes: '0x1C',
      category: 'colour',
      description: 'Text colour red (CHR$ 28).',
      example: {
        source: '{red}',
        bytes: [28],
      },
      codes: [28],
    },
    {
      escape: '{green}',
      bytes: '0x1E',
      category: 'colour',
      description: 'Text colour green (CHR$ 30).',
      aliases: ['{grn}'],
      example: {
        source: '{green}',
        bytes: [30],
      },
      codes: [30],
    },
    {
      escape: '{blue}',
      bytes: '0x1F',
      category: 'colour',
      description: 'Text colour blue (CHR$ 31).',
      aliases: ['{blu}'],
      example: {
        source: '{blue}',
        bytes: [31],
      },
      codes: [31],
    },
    {
      escape: '{orange}',
      bytes: '0x81',
      category: 'colour',
      description: 'Text colour orange (CHR$ 129).',
      aliases: ['{orng}'],
      example: {
        source: '{orange}',
        bytes: [129],
      },
      codes: [129],
    },
    {
      escape: '{black}',
      bytes: '0x90',
      category: 'colour',
      description: 'Text colour black (CHR$ 144).',
      aliases: ['{blk}'],
      example: {
        source: '{black}',
        bytes: [144],
      },
      codes: [144],
    },
    {
      escape: '{brown}',
      bytes: '0x95',
      category: 'colour',
      description: 'Text colour brown (CHR$ 149).',
      aliases: ['{brn}'],
      example: {
        source: '{brown}',
        bytes: [149],
      },
      codes: [149],
    },
    {
      escape: '{pink}',
      bytes: '0x96',
      category: 'colour',
      description: 'Text colour pink / light red (CHR$ 150).',
      aliases: ['{lred}'],
      example: {
        source: '{pink}',
        bytes: [150],
      },
      codes: [150],
    },
    {
      escape: '{grey1}',
      bytes: '0x97',
      category: 'colour',
      description: 'Text colour dark grey (CHR$ 151).',
      aliases: ['{gry1}'],
      example: {
        source: '{grey1}',
        bytes: [151],
      },
      codes: [151],
    },
    {
      escape: '{grey2}',
      bytes: '0x98',
      category: 'colour',
      description: 'Text colour medium grey (CHR$ 152).',
      aliases: ['{gry2}'],
      example: {
        source: '{grey2}',
        bytes: [152],
      },
      codes: [152],
    },
    {
      escape: '{lgreen}',
      bytes: '0x99',
      category: 'colour',
      description: 'Text colour light green (CHR$ 153).',
      aliases: ['{lgrn}'],
      example: {
        source: '{lgreen}',
        bytes: [153],
      },
      codes: [153],
    },
    {
      escape: '{lblue}',
      bytes: '0x9A',
      category: 'colour',
      description: 'Text colour light blue (CHR$ 154).',
      aliases: ['{lblu}'],
      example: {
        source: '{lblue}',
        bytes: [154],
      },
      codes: [154],
    },
    {
      escape: '{grey3}',
      bytes: '0x9B',
      category: 'colour',
      description: 'Text colour light grey (CHR$ 155).',
      aliases: ['{gry3}'],
      example: {
        source: '{grey3}',
        bytes: [155],
      },
      codes: [155],
    },
    {
      escape: '{purple}',
      bytes: '0x9C',
      category: 'colour',
      description: 'Text colour purple (CHR$ 156).',
      aliases: ['{pur}'],
      example: {
        source: '{purple}',
        bytes: [156],
      },
      codes: [156],
    },
    {
      escape: '{yellow}',
      bytes: '0x9E',
      category: 'colour',
      description: 'Text colour yellow (CHR$ 158).',
      aliases: ['{yel}'],
      example: {
        source: '{yellow}',
        bytes: [158],
      },
      codes: [158],
    },
    {
      escape: '{cyan}',
      bytes: '0x9F',
      category: 'colour',
      description: 'Text colour cyan (CHR$ 159).',
      aliases: ['{cyn}'],
      example: {
        source: '{cyan}',
        bytes: [159],
      },
      codes: [159],
    },
    {
      escape: '{down}',
      bytes: '0x11',
      category: 'cursor',
      description: 'Cursor down one row (CHR$ 17).',
      example: {
        source: '{down}',
        bytes: [17],
      },
      codes: [17],
    },
    {
      escape: '{right}',
      bytes: '0x1D',
      category: 'cursor',
      description: 'Cursor right one column (CHR$ 29).',
      aliases: ['{rght}'],
      example: {
        source: '{right}',
        bytes: [29],
      },
      codes: [29],
    },
    {
      escape: '{up}',
      bytes: '0x91',
      category: 'cursor',
      description: 'Cursor up one row (CHR$ 145).',
      example: {
        source: '{up}',
        bytes: [145],
      },
      codes: [145],
    },
    {
      escape: '{left}',
      bytes: '0x9D',
      category: 'cursor',
      description: 'Cursor left one column (CHR$ 157).',
      example: {
        source: '{left}',
        bytes: [157],
      },
      codes: [157],
    },
    {
      escape: '{home}',
      bytes: '0x13',
      category: 'cursor',
      description: 'Cursor home - top-left of the screen (CHR$ 19).',
      example: {
        source: '{home}',
        bytes: [19],
      },
      codes: [19],
    },
    {
      escape: '{clr}',
      bytes: '0x93',
      category: 'editing',
      description: 'Clear the screen and home the cursor (CHR$ 147).',
      example: {
        source: '{clr}',
        bytes: [147],
      },
      codes: [147],
    },
    {
      escape: '{del}',
      bytes: '0x14',
      category: 'editing',
      description: 'Delete the character before the cursor (CHR$ 20).',
      example: {
        source: '{del}',
        bytes: [20],
      },
      codes: [20],
    },
    {
      escape: '{inst}',
      bytes: '0x94',
      category: 'editing',
      description: 'Insert a space at the cursor (CHR$ 148).',
      example: {
        source: '{inst}',
        bytes: [148],
      },
      codes: [148],
    },
    {
      escape: '{cr}',
      bytes: '0x0D',
      category: 'editing',
      description: 'Carriage return (CHR$ 13).',
      example: {
        source: '{cr}',
        bytes: [13],
      },
      codes: [13],
    },
    {
      escape: '{shift-cr}',
      bytes: '0x8D',
      category: 'editing',
      description:
        'Shifted return (CHR$ 141): moves to the next line without executing it.',
      aliases: ['{sret}'],
      example: {
        source: '{shift-cr}',
        bytes: [141],
      },
      codes: [141],
    },
    {
      escape: '{rvon}',
      bytes: '0x12',
      category: 'mode',
      description: 'Reverse video on (CHR$ 18).',
      example: {
        source: '{rvon}',
        bytes: [18],
      },
      codes: [18],
    },
    {
      escape: '{rvoff}',
      bytes: '0x92',
      category: 'mode',
      description: 'Reverse video off (CHR$ 146).',
      aliases: ['{rvof}'],
      example: {
        source: '{rvoff}',
        bytes: [146],
      },
      codes: [146],
    },
    {
      escape: '{lower}',
      bytes: '0x0E',
      category: 'mode',
      description:
        'Switch the display to the lower-case / upper-case character set (CHR$ 14).',
      aliases: ['{swlc}'],
      example: {
        source: '{lower}',
        bytes: [14],
      },
      codes: [14],
    },
    {
      escape: '{upper}',
      bytes: '0x8E',
      category: 'mode',
      description:
        'Switch the display to the upper-case / graphics character set (CHR$ 142).',
      aliases: ['{swuc}'],
      example: {
        source: '{upper}',
        bytes: [142],
      },
      codes: [142],
    },
    {
      escape: '{dishift}',
      bytes: '0x08',
      category: 'mode',
      description: 'Disable SHIFT+C= case switching (CHR$ 8).',
      example: {
        source: '{dishift}',
        bytes: [8],
      },
      codes: [8],
    },
    {
      escape: '{enshift}',
      bytes: '0x09',
      category: 'mode',
      description: 'Enable SHIFT+C= case switching (CHR$ 9).',
      example: {
        source: '{enshift}',
        bytes: [9],
      },
      codes: [9],
    },
    {
      escape: '{f1}',
      bytes: '0x85',
      category: 'keys',
      description: 'Function key f1 (CHR$ 133).',
      example: {
        source: '{f1}',
        bytes: [133],
      },
      codes: [133],
    },
    {
      escape: '{f2}',
      bytes: '0x89',
      category: 'keys',
      description: 'Function key f2 (CHR$ 137).',
      example: {
        source: '{f2}',
        bytes: [137],
      },
      codes: [137],
    },
    {
      escape: '{f3}',
      bytes: '0x86',
      category: 'keys',
      description: 'Function key f3 (CHR$ 134).',
      example: {
        source: '{f3}',
        bytes: [134],
      },
      codes: [134],
    },
    {
      escape: '{f4}',
      bytes: '0x8A',
      category: 'keys',
      description: 'Function key f4 (CHR$ 138).',
      example: {
        source: '{f4}',
        bytes: [138],
      },
      codes: [138],
    },
    {
      escape: '{f5}',
      bytes: '0x87',
      category: 'keys',
      description: 'Function key f5 (CHR$ 135).',
      example: {
        source: '{f5}',
        bytes: [135],
      },
      codes: [135],
    },
    {
      escape: '{f6}',
      bytes: '0x8B',
      category: 'keys',
      description: 'Function key f6 (CHR$ 139).',
      example: {
        source: '{f6}',
        bytes: [139],
      },
      codes: [139],
    },
    {
      escape: '{f7}',
      bytes: '0x88',
      category: 'keys',
      description: 'Function key f7 (CHR$ 136).',
      example: {
        source: '{f7}',
        bytes: [136],
      },
      codes: [136],
    },
    {
      escape: '{f8}',
      bytes: '0x8C',
      category: 'keys',
      description: 'Function key f8 (CHR$ 140).',
      example: {
        source: '{f8}',
        bytes: [140],
      },
      codes: [140],
    },
    {
      escape: '{stop}',
      bytes: '0x03',
      category: 'control',
      description: 'The STOP key code (CHR$ 3).',
      example: {
        source: '{stop}',
        bytes: [3],
      },
      codes: [3],
    },
    {
      escape: '{shift-space}',
      bytes: '0xA0',
      category: 'character',
      description:
        'Shifted space (CHR$ 160): displays as a space but is a distinct code.',
      example: {
        source: '{shift-space}',
        bytes: [160],
      },
      codes: [160],
    },
    {
      escape: '{space}',
      bytes: '0x20',
      category: 'character',
      description: 'An ordinary space (CHR$ 32), petcat spelling.',
      example: {
        source: '{space}',
        bytes: [32],
      },
      parseOnly: true,
    },
    {
      escape: '{CBM-a}',
      bytes: '0xB0',
      category: 'key-graphics',
      description: 'Block graphic on the C= face of the A key (┌).',
      example: {
        source: '{CBM-a}',
        bytes: [176],
      },
      parseOnly: true,
    },
    {
      escape: '{CBM-b}',
      bytes: '0xBF',
      category: 'key-graphics',
      description: 'Block graphic on the C= face of the B key (▚).',
      example: {
        source: '{CBM-b}',
        bytes: [191],
      },
      parseOnly: true,
    },
    {
      escape: '{CBM-c}',
      bytes: '0xBC',
      category: 'key-graphics',
      description: 'Block graphic on the C= face of the C key (▝).',
      example: {
        source: '{CBM-c}',
        bytes: [188],
      },
      parseOnly: true,
    },
    {
      escape: '{CBM-d}',
      bytes: '0xAC',
      category: 'key-graphics',
      description: 'Block graphic on the C= face of the D key (▗).',
      example: {
        source: '{CBM-d}',
        bytes: [172],
      },
      parseOnly: true,
    },
    {
      escape: '{CBM-e}',
      bytes: '0xB1',
      category: 'key-graphics',
      description: 'Block graphic on the C= face of the E key (┴).',
      example: {
        source: '{CBM-e}',
        bytes: [177],
      },
      parseOnly: true,
    },
    {
      escape: '{CBM-f}',
      bytes: '0xBB',
      category: 'key-graphics',
      description: 'Block graphic on the C= face of the F key (▖).',
      example: {
        source: '{CBM-f}',
        bytes: [187],
      },
      parseOnly: true,
    },
    {
      escape: '{CBM-g}',
      bytes: '0xA5',
      category: 'key-graphics',
      description: 'Block graphic on the C= face of the G key (▎).',
      example: {
        source: '{CBM-g}',
        bytes: [165],
      },
      parseOnly: true,
    },
    {
      escape: '{CBM-h}',
      bytes: '0xB4',
      category: 'key-graphics',
      description:
        'Block graphic on the C= face of the H key (▎). This code is a hardware duplicate glyph, so it decodes back as a raw {$b4} escape.',
      example: {
        source: '{CBM-h}',
        bytes: [180],
      },
      parseOnly: true,
    },
    {
      escape: '{CBM-i}',
      bytes: '0xA2',
      category: 'key-graphics',
      description: 'Block graphic on the C= face of the I key (▄).',
      example: {
        source: '{CBM-i}',
        bytes: [162],
      },
      parseOnly: true,
    },
    {
      escape: '{CBM-j}',
      bytes: '0xB5',
      category: 'key-graphics',
      description: 'Block graphic on the C= face of the J key (▍).',
      example: {
        source: '{CBM-j}',
        bytes: [181],
      },
      parseOnly: true,
    },
    {
      escape: '{CBM-k}',
      bytes: '0xA1',
      category: 'key-graphics',
      description: 'Block graphic on the C= face of the K key (▌).',
      example: {
        source: '{CBM-k}',
        bytes: [161],
      },
      parseOnly: true,
    },
    {
      escape: '{CBM-l}',
      bytes: '0xB6',
      category: 'key-graphics',
      description: 'Block graphic on the C= face of the L key (🮈).',
      example: {
        source: '{CBM-l}',
        bytes: [182],
      },
      parseOnly: true,
    },
    {
      escape: '{CBM-m}',
      bytes: '0xA7',
      category: 'key-graphics',
      description: 'Block graphic on the C= face of the M key (▕).',
      example: {
        source: '{CBM-m}',
        bytes: [167],
      },
      parseOnly: true,
    },
    {
      escape: '{CBM-n}',
      bytes: '0xAA',
      category: 'key-graphics',
      description:
        'Block graphic on the C= face of the N key (▕). This code is a hardware duplicate glyph, so it decodes back as a raw {$aa} escape.',
      example: {
        source: '{CBM-n}',
        bytes: [170],
      },
      parseOnly: true,
    },
    {
      escape: '{CBM-o}',
      bytes: '0xB9',
      category: 'key-graphics',
      description: 'Block graphic on the C= face of the O key (▃).',
      example: {
        source: '{CBM-o}',
        bytes: [185],
      },
      parseOnly: true,
    },
    {
      escape: '{CBM-p}',
      bytes: '0xAF',
      category: 'key-graphics',
      description: 'Block graphic on the C= face of the P key (▂).',
      example: {
        source: '{CBM-p}',
        bytes: [175],
      },
      parseOnly: true,
    },
    {
      escape: '{CBM-q}',
      bytes: '0xAB',
      category: 'key-graphics',
      description: 'Block graphic on the C= face of the Q key (├).',
      example: {
        source: '{CBM-q}',
        bytes: [171],
      },
      parseOnly: true,
    },
    {
      escape: '{CBM-r}',
      bytes: '0xB2',
      category: 'key-graphics',
      description: 'Block graphic on the C= face of the R key (┬).',
      example: {
        source: '{CBM-r}',
        bytes: [178],
      },
      parseOnly: true,
    },
    {
      escape: '{CBM-s}',
      bytes: '0xAE',
      category: 'key-graphics',
      description: 'Block graphic on the C= face of the S key (┐).',
      example: {
        source: '{CBM-s}',
        bytes: [174],
      },
      parseOnly: true,
    },
    {
      escape: '{CBM-t}',
      bytes: '0xA3',
      category: 'key-graphics',
      description: 'Block graphic on the C= face of the T key (▔).',
      example: {
        source: '{CBM-t}',
        bytes: [163],
      },
      parseOnly: true,
    },
    {
      escape: '{CBM-u}',
      bytes: '0xB8',
      category: 'key-graphics',
      description: 'Block graphic on the C= face of the U key (🮃).',
      example: {
        source: '{CBM-u}',
        bytes: [184],
      },
      parseOnly: true,
    },
    {
      escape: '{CBM-v}',
      bytes: '0xBE',
      category: 'key-graphics',
      description: 'Block graphic on the C= face of the V key (▘).',
      example: {
        source: '{CBM-v}',
        bytes: [190],
      },
      parseOnly: true,
    },
    {
      escape: '{CBM-w}',
      bytes: '0xB3',
      category: 'key-graphics',
      description: 'Block graphic on the C= face of the W key (┤).',
      example: {
        source: '{CBM-w}',
        bytes: [179],
      },
      parseOnly: true,
    },
    {
      escape: '{CBM-x}',
      bytes: '0xBD',
      category: 'key-graphics',
      description: 'Block graphic on the C= face of the X key (┘).',
      example: {
        source: '{CBM-x}',
        bytes: [189],
      },
      parseOnly: true,
    },
    {
      escape: '{CBM-y}',
      bytes: '0xB7',
      category: 'key-graphics',
      description: 'Block graphic on the C= face of the Y key (🮂).',
      example: {
        source: '{CBM-y}',
        bytes: [183],
      },
      parseOnly: true,
    },
    {
      escape: '{CBM-z}',
      bytes: '0xAD',
      category: 'key-graphics',
      description: 'Block graphic on the C= face of the Z key (└).',
      example: {
        source: '{CBM-z}',
        bytes: [173],
      },
      parseOnly: true,
    },
    {
      escape: '{SHIFT-a}',
      bytes: '0xC1',
      category: 'key-graphics',
      description: 'Graphic on the SHIFT face of the A key (♠).',
      example: {
        source: '{SHIFT-a}',
        bytes: [193],
      },
      parseOnly: true,
    },
    {
      escape: '{SHIFT-b}',
      bytes: '0xC2',
      category: 'key-graphics',
      description: 'Graphic on the SHIFT face of the B key (│).',
      example: {
        source: '{SHIFT-b}',
        bytes: [194],
      },
      parseOnly: true,
    },
    {
      escape: '{SHIFT-c}',
      bytes: '0xC3',
      category: 'key-graphics',
      description:
        'Graphic on the SHIFT face of the C key (─). This code is a hardware duplicate glyph, so it decodes back as a raw {$c3} escape.',
      example: {
        source: '{SHIFT-c}',
        bytes: [195],
      },
      parseOnly: true,
    },
    {
      escape: '{SHIFT-d}',
      bytes: '0xC4',
      category: 'key-graphics',
      description: 'Graphic on the SHIFT face of the D key (🭷).',
      example: {
        source: '{SHIFT-d}',
        bytes: [196],
      },
      parseOnly: true,
    },
    {
      escape: '{SHIFT-e}',
      bytes: '0xC5',
      category: 'key-graphics',
      description: 'Graphic on the SHIFT face of the E key (🭶).',
      example: {
        source: '{SHIFT-e}',
        bytes: [197],
      },
      parseOnly: true,
    },
    {
      escape: '{SHIFT-f}',
      bytes: '0xC6',
      category: 'key-graphics',
      description: 'Graphic on the SHIFT face of the F key (🭹).',
      example: {
        source: '{SHIFT-f}',
        bytes: [198],
      },
      parseOnly: true,
    },
    {
      escape: '{SHIFT-g}',
      bytes: '0xC7',
      category: 'key-graphics',
      description: 'Graphic on the SHIFT face of the G key (🭱).',
      example: {
        source: '{SHIFT-g}',
        bytes: [199],
      },
      parseOnly: true,
    },
    {
      escape: '{SHIFT-h}',
      bytes: '0xC8',
      category: 'key-graphics',
      description: 'Graphic on the SHIFT face of the H key (🭳).',
      example: {
        source: '{SHIFT-h}',
        bytes: [200],
      },
      parseOnly: true,
    },
    {
      escape: '{SHIFT-i}',
      bytes: '0xC9',
      category: 'key-graphics',
      description: 'Graphic on the SHIFT face of the I key (╮).',
      example: {
        source: '{SHIFT-i}',
        bytes: [201],
      },
      parseOnly: true,
    },
    {
      escape: '{SHIFT-j}',
      bytes: '0xCA',
      category: 'key-graphics',
      description: 'Graphic on the SHIFT face of the J key (╰).',
      example: {
        source: '{SHIFT-j}',
        bytes: [202],
      },
      parseOnly: true,
    },
    {
      escape: '{SHIFT-k}',
      bytes: '0xCB',
      category: 'key-graphics',
      description: 'Graphic on the SHIFT face of the K key (╯).',
      example: {
        source: '{SHIFT-k}',
        bytes: [203],
      },
      parseOnly: true,
    },
    {
      escape: '{SHIFT-l}',
      bytes: '0xCC',
      category: 'key-graphics',
      description: 'Graphic on the SHIFT face of the L key (⌞).',
      example: {
        source: '{SHIFT-l}',
        bytes: [204],
      },
      parseOnly: true,
    },
    {
      escape: '{SHIFT-m}',
      bytes: '0xCD',
      category: 'key-graphics',
      description: 'Graphic on the SHIFT face of the M key (╲).',
      example: {
        source: '{SHIFT-m}',
        bytes: [205],
      },
      parseOnly: true,
    },
    {
      escape: '{SHIFT-n}',
      bytes: '0xCE',
      category: 'key-graphics',
      description: 'Graphic on the SHIFT face of the N key (╱).',
      example: {
        source: '{SHIFT-n}',
        bytes: [206],
      },
      parseOnly: true,
    },
    {
      escape: '{SHIFT-o}',
      bytes: '0xCF',
      category: 'key-graphics',
      description: 'Graphic on the SHIFT face of the O key (⌜).',
      example: {
        source: '{SHIFT-o}',
        bytes: [207],
      },
      parseOnly: true,
    },
    {
      escape: '{SHIFT-p}',
      bytes: '0xD0',
      category: 'key-graphics',
      description: 'Graphic on the SHIFT face of the P key (⌝).',
      example: {
        source: '{SHIFT-p}',
        bytes: [208],
      },
      parseOnly: true,
    },
    {
      escape: '{SHIFT-q}',
      bytes: '0xD1',
      category: 'key-graphics',
      description: 'Graphic on the SHIFT face of the Q key (●).',
      example: {
        source: '{SHIFT-q}',
        bytes: [209],
      },
      parseOnly: true,
    },
    {
      escape: '{SHIFT-r}',
      bytes: '0xD2',
      category: 'key-graphics',
      description: 'Graphic on the SHIFT face of the R key (_).',
      example: {
        source: '{SHIFT-r}',
        bytes: [210],
      },
      parseOnly: true,
    },
    {
      escape: '{SHIFT-s}',
      bytes: '0xD3',
      category: 'key-graphics',
      description: 'Graphic on the SHIFT face of the S key (♥).',
      example: {
        source: '{SHIFT-s}',
        bytes: [211],
      },
      parseOnly: true,
    },
    {
      escape: '{SHIFT-t}',
      bytes: '0xD4',
      category: 'key-graphics',
      description: 'Graphic on the SHIFT face of the T key (🭰).',
      example: {
        source: '{SHIFT-t}',
        bytes: [212],
      },
      parseOnly: true,
    },
    {
      escape: '{SHIFT-u}',
      bytes: '0xD5',
      category: 'key-graphics',
      description: 'Graphic on the SHIFT face of the U key (╭).',
      example: {
        source: '{SHIFT-u}',
        bytes: [213],
      },
      parseOnly: true,
    },
    {
      escape: '{SHIFT-v}',
      bytes: '0xD6',
      category: 'key-graphics',
      description: 'Graphic on the SHIFT face of the V key (╳).',
      example: {
        source: '{SHIFT-v}',
        bytes: [214],
      },
      parseOnly: true,
    },
    {
      escape: '{SHIFT-w}',
      bytes: '0xD7',
      category: 'key-graphics',
      description: 'Graphic on the SHIFT face of the W key (○).',
      example: {
        source: '{SHIFT-w}',
        bytes: [215],
      },
      parseOnly: true,
    },
    {
      escape: '{SHIFT-x}',
      bytes: '0xD8',
      category: 'key-graphics',
      description: 'Graphic on the SHIFT face of the X key (♣).',
      example: {
        source: '{SHIFT-x}',
        bytes: [216],
      },
      parseOnly: true,
    },
    {
      escape: '{SHIFT-y}',
      bytes: '0xD9',
      category: 'key-graphics',
      description: 'Graphic on the SHIFT face of the Y key (🭴).',
      example: {
        source: '{SHIFT-y}',
        bytes: [217],
      },
      parseOnly: true,
    },
    {
      escape: '{SHIFT-z}',
      bytes: '0xDA',
      category: 'key-graphics',
      description: 'Graphic on the SHIFT face of the Z key (♦).',
      example: {
        source: '{SHIFT-z}',
        bytes: [218],
      },
      parseOnly: true,
    },
    {
      escape: '{$xx}',
      bytes: 'any',
      category: 'raw',
      description:
        'Any raw byte as one or two hex digits - unassigned control codes, the shifted-bank text range $60-$7F, $E0-$FE and the hardware-duplicate glyph codes ($AA, $B4, $C3, $DD, $DE). The lower-case display bank and keyword abbreviations are not yet modelled.',
      example: {
        source: '{$60}',
        bytes: [96],
      },
      codes: 'rest',
    },
    {
      escape: '{nnn}',
      bytes: 'any',
      category: 'raw',
      description:
        'Any raw byte as a decimal code 0-255 (petcat/VICE spelling), e.g. {147} for {clr}.',
      example: {
        source: '{163}',
        bytes: [163],
      },
      parseOnly: true,
    },
  ],
};
