// Escape-code table for the ZX81 escapes page. Grounded in
// src/dialects/zx81/charset.ts (+ sinclairCharset.ts, zxfloat.ts) and pinned
// against the implementation by escapes/escape-crosscheck.test.ts.
import type { EscapeTableData } from '../types';
import { range } from './util';

export const zx81Escapes: EscapeTableData = {
  title: 'ZX81 escape codes',
  machines: ['Sinclair ZX81'],
  categories: [
    { id: 'graphics', label: 'Block graphics' },
    { id: 'inverse', label: 'Inverse video' },
    { id: 'numeric', label: 'Numeric overrides' },
    { id: 'raw', label: 'Raw bytes' },
  ],
  entries: [
    // Backslash graphics escapes (zxtext2p convention): two characters naming
    // the left and right column of the cell - ' = top, . = bottom, : = full,
    // space = empty; ! = grey, | = inverse grey. Codes with an exact unicode
    // block glyph decode to the glyph, so those spellings are parse-only.
    {
      escape: "\\' ",
      bytes: '0x01',
      category: 'graphics',
      description: 'Top-left quarter block.',
      aliases: ['▘'],
      parseOnly: true,
      example: { source: "\\' ", bytes: [0x01] },
    },
    {
      escape: "\\ '",
      bytes: '0x02',
      category: 'graphics',
      description: 'Top-right quarter block.',
      aliases: ['▝'],
      parseOnly: true,
      example: { source: "\\ '", bytes: [0x02] },
    },
    {
      escape: "\\''",
      bytes: '0x03',
      category: 'graphics',
      description: 'Top half block.',
      aliases: ['▀'],
      parseOnly: true,
      example: { source: "\\''", bytes: [0x03] },
    },
    {
      escape: '\\. ',
      bytes: '0x04',
      category: 'graphics',
      description: 'Bottom-left quarter block.',
      aliases: ['▖'],
      parseOnly: true,
      example: { source: '\\. ', bytes: [0x04] },
    },
    {
      escape: '\\: ',
      bytes: '0x05',
      category: 'graphics',
      description: 'Left half block.',
      aliases: ['▌'],
      parseOnly: true,
      example: { source: '\\: ', bytes: [0x05] },
    },
    {
      escape: "\\.'",
      bytes: '0x06',
      category: 'graphics',
      description: 'Bottom-left and top-right quarters.',
      aliases: ['▞'],
      parseOnly: true,
      example: { source: "\\.'", bytes: [0x06] },
    },
    {
      escape: "\\:'",
      bytes: '0x07',
      category: 'graphics',
      description: 'All quarters except bottom-right.',
      aliases: ['▛'],
      parseOnly: true,
      example: { source: "\\:'", bytes: [0x07] },
    },
    {
      escape: '\\!!',
      bytes: '0x08',
      category: 'graphics',
      description: 'Grey (chequerboard) block.',
      aliases: ['▒'],
      parseOnly: true,
      example: { source: '\\!!', bytes: [0x08] },
    },
    {
      escape: "\\!'",
      bytes: '0x0A',
      category: 'graphics',
      description: 'Grey upper half.',
      aliases: ['🮎'],
      parseOnly: true,
      example: { source: "\\!'", bytes: [0x0a] },
    },
    {
      escape: '\\!.',
      bytes: '0x09',
      category: 'graphics',
      description: 'Grey lower half.',
      aliases: ['🮏'],
      parseOnly: true,
      example: { source: '\\!.', bytes: [0x09] },
    },
    {
      escape: '\\::',
      bytes: '0x80',
      category: 'graphics',
      description: 'Full block (inverse space).',
      aliases: ['█'],
      parseOnly: true,
      example: { source: '\\::', bytes: [0x80] },
    },
    {
      escape: '\\.:',
      bytes: '0x81',
      category: 'graphics',
      description: 'All quarters except top-left.',
      aliases: ['▟'],
      parseOnly: true,
      example: { source: '\\.:', bytes: [0x81] },
    },
    {
      escape: '\\:.',
      bytes: '0x82',
      category: 'graphics',
      description: 'All quarters except top-right.',
      aliases: ['▙'],
      parseOnly: true,
      example: { source: '\\:.', bytes: [0x82] },
    },
    {
      escape: '\\..',
      bytes: '0x83',
      category: 'graphics',
      description: 'Bottom half block.',
      aliases: ['▄'],
      parseOnly: true,
      example: { source: '\\..', bytes: [0x83] },
    },
    {
      escape: "\\':",
      bytes: '0x84',
      category: 'graphics',
      description: 'All quarters except bottom-left.',
      aliases: ['▜'],
      parseOnly: true,
      example: { source: "\\':", bytes: [0x84] },
    },
    {
      escape: '\\ :',
      bytes: '0x85',
      category: 'graphics',
      description: 'Right half block.',
      aliases: ['▐'],
      parseOnly: true,
      example: { source: '\\ :', bytes: [0x85] },
    },
    {
      escape: "\\'.",
      bytes: '0x86',
      category: 'graphics',
      description: 'Top-left and bottom-right quarters.',
      aliases: ['▚'],
      parseOnly: true,
      example: { source: "\\'.", bytes: [0x86] },
    },
    {
      escape: '\\ .',
      bytes: '0x87',
      category: 'graphics',
      description: 'Bottom-right quarter block.',
      aliases: ['▗'],
      parseOnly: true,
      example: { source: '\\ .', bytes: [0x87] },
    },
    {
      escape: '\\||',
      bytes: '0x88',
      category: 'graphics',
      description: 'Inverse grey block.',
      aliases: ['🮐'],
      parseOnly: true,
      example: { source: '\\||', bytes: [0x88] },
    },
    {
      escape: "\\|'",
      bytes: '0x8A',
      category: 'graphics',
      description: 'Inverse grey upper half over solid lower half.',
      aliases: ['🮒'],
      parseOnly: true,
      example: { source: "\\|'", bytes: [0x8a] },
    },
    {
      escape: '\\|.',
      bytes: '0x89',
      category: 'graphics',
      description: 'Solid upper half over inverse grey lower half.',
      aliases: ['🮑'],
      parseOnly: true,
      example: { source: '\\|.', bytes: [0x89] },
    },
    {
      escape: '%c',
      bytes: '0x8B–0xBF',
      category: 'inverse',
      description:
        'Inverse video: % before a letter, digit or punctuation character stores its inverse-video code, e.g. %A is inverse A.',
      codes: range(0x8b, 0xbf),
      example: { source: '%A', bytes: [0xa6] },
    },
    {
      escape: '\\{=n}',
      bytes: '0x7E + 5-byte float',
      category: 'numeric',
      description:
        'Numeric override after a literal: the hidden 5-byte float stored with the printed digits encodes n instead (protection tricks, e.g. 20\\{=9999}). Emitted on import when the stored float disagrees with the digits.',
      probe: 'float',
      example: { source: '\\{=9999}', bytes: [0x8e, 0x1c, 0x3c, 0x00, 0x00] },
    },
    {
      escape: '\\{=$HHHHHHHHHH}',
      bytes: '0x7E + 5-byte float',
      category: 'numeric',
      description:
        'Raw form of a numeric override whose 5 stored bytes are not the canonical encoding of any decimal value.',
      probe: 'float',
      example: {
        source: '\\{=$8E1C3C0000}',
        bytes: [0x8e, 0x1c, 0x3c, 0x00, 0x00],
      },
    },
    {
      escape: '\\{NN}',
      bytes: 'any',
      category: 'raw',
      description:
        'Any raw byte as two hex digits - keyword tokens inside strings, control codes (e.g. \\{76} NEWLINE), trailing REM spaces (\\{00}) and every other byte with no printable form.',
      codes: 'rest',
      example: { source: '\\{76}', bytes: [0x76] },
    },
  ],
};
