import type {
  Dialect,
  MachineEmulator,
  TokenizeError,
  TokenizeResult,
} from '../types';
import { cpc464Keywords } from './keywords';
import { cpcCharset } from './charset';
import { cpcLanguageSupport, cpcCompletionSource } from './language';
import { cpc464KeyboardLayout } from './keyboardLayout';
import { cpc464Samples } from './samples';
import { cpc464BuildTargets } from './targets';
import { cpc464AiProfile } from './aiProfile';

/**
 * Amstrad CPC 464 (Locomotive BASIC 1.0) — SCAFFOLDING ONLY.
 *
 * Throwing stubs generated by the `adding-a-target-system` skill; the staged
 * plan lives at docs/contributing/dialect-plans/cpc464.md. Intentionally NOT
 * registered in src/dialects/registry.ts until the plan's Stage 3 (which also
 * adds the `mode` share verb to src/player/routes.ts in the same change).
 * The CPC 6128 sibling (../cpc6128/) delegates to this dialect.
 */
export const cpc464: Dialect = {
  id: 'cpc464',
  name: 'CPC 464',
  docsReference: 'cpc',
  // PRINT FRE(0) on a clean 464 boot (BASIC 1.0, no AMSDOS).
  programRamBytes: 42619,
  fileExtensions: ['.txt', '.bas'],
  keywords: cpc464Keywords,
  charset: cpcCharset,
  languageSupport: cpcLanguageSupport,
  completionSource: cpcCompletionSource,

  tokenize(_source: string): TokenizeResult {
    throw new Error('cpc464: not implemented');
  },

  detokenize(_image: Uint8Array): string {
    throw new Error('cpc464: not implemented');
  },

  lint(_source: string): TokenizeError[] {
    throw new Error('cpc464: not implemented');
  },

  createEmulator(_opts): MachineEmulator {
    throw new Error('cpc464: not implemented');
  },

  keyboardLayout: cpc464KeyboardLayout,

  samples: cpc464Samples,

  buildTargets: cpc464BuildTargets,

  aiProfile: cpc464AiProfile,
};
