// Reference table data for the Amstrad CPC Locomotive BASIC (1.0 & 1.1) page.
// Seeded from the dialect's keyword table by scripts/gen-reference-scaffold.mts,
// then hand-enriched (typed <…> syntax + fuller descriptions). Edit by hand;
// the generator skips this file once it exists.
import type { BasicReferenceTableData } from './types';

export const cpcReference: BasicReferenceTableData = {
  title: 'Amstrad CPC Locomotive BASIC (1.0 & 1.1)',
  machines: ['Amstrad CPC 464', 'Amstrad CPC 6128'],
  placeholders: [
    { id: 'pen', meaning: 'a pen number in the current palette' },
    { id: 'stream', meaning: 'one of the eight screen windows, #0 to #7' },
    { id: 'timer', meaning: 'one of the four delay timers, 0 to 3' },
    { id: 'key', meaning: 'a key, by its key number' },
    { id: 'period', meaning: 'a tone period: 62500 divided by the frequency' },
    { id: 'volume', meaning: 'how loud a sound is' },
    {
      id: 'volenv',
      meaning: 'a volume envelope, by number, as defined by ENV',
    },
    { id: 'toneenv', meaning: 'a tone envelope, by number, as defined by ENT' },
    { id: 'noise', meaning: 'a noise period, 0 to 31' },
    {
      id: 'section',
      meaning: 'one envelope section: step count, step size and pause',
    },
    { id: 'left', meaning: 'the left edge of a window or clipping area' },
    { id: 'right', meaning: 'the right edge of a window or clipping area' },
    { id: 'top', meaning: 'the top edge of a window or clipping area' },
    { id: 'bottom', meaning: 'the bottom edge of a window or clipping area' },
  ],
  entries: [
    {
      name: 'AFTER',
      kind: 'command',
      domain: 'control-flow',
      syntax: 'AFTER <number>[, <timer>] GOSUB <line>',
      description: 'Call a subroutine after a delay (1/50s units).',
    },
    {
      name: 'AUTO',
      kind: 'command',
      domain: 'program-editing',
      syntax: 'AUTO [<line>][, <number>]',
      description: 'Automatic line numbering (editor command).',
    },
    {
      name: 'BORDER',
      kind: 'command',
      domain: 'colour',
      syntax: 'BORDER <colour>[, <colour>]',
      description: 'Set the border colour (two colours flash).',
    },
    {
      name: 'CALL',
      kind: 'command',
      domain: 'memory-hardware',
      syntax: 'CALL <addr>[, <arg>]…',
      description: 'Call a machine-code routine.',
    },
    {
      name: 'CAT',
      kind: 'command',
      domain: 'storage',
      syntax: 'CAT',
      description: 'Catalogue the cassette/disc.',
    },
    {
      name: 'CHAIN',
      kind: 'command',
      domain: 'storage',
      syntax: 'CHAIN <filename>[, <line>]',
      description: 'Load and run another program.',
    },
    {
      name: 'CLEAR',
      kind: 'command',
      domain: 'data',
      syntax: 'CLEAR',
      description: 'Clear all variables.',
    },
    {
      name: 'CLG',
      kind: 'command',
      domain: 'graphics',
      syntax: 'CLG [<pen>]',
      description: 'Clear the graphics screen.',
    },
    {
      name: 'CLOSEIN',
      kind: 'command',
      domain: 'storage',
      syntax: 'CLOSEIN',
      description: 'Close the input file.',
    },
    {
      name: 'CLOSEOUT',
      kind: 'command',
      domain: 'storage',
      syntax: 'CLOSEOUT',
      description: 'Close the output file.',
    },
    {
      name: 'CLS',
      kind: 'command',
      domain: 'text-screen',
      syntax: 'CLS [#<stream>]',
      description: 'Clear the screen (or a window).',
    },
    {
      name: 'CONT',
      kind: 'command',
      domain: 'program-editing',
      syntax: 'CONT',
      description: 'Continue after break or STOP.',
    },
    {
      name: 'DATA',
      kind: 'command',
      domain: 'data',
      syntax: 'DATA <constant>[, <constant>]…',
      description: 'Inline data for READ.',
    },
    {
      name: 'DEF',
      kind: 'command',
      domain: 'control-flow',
      syntax: 'DEF FN<name>[(<param>[, <param>]…)] = <expr>',
      description: 'Define a function.',
    },
    {
      name: 'DEFINT',
      kind: 'command',
      domain: 'data',
      syntax: 'DEFINT <letter>[-<letter>]',
      description: 'Default listed initial letters to integer type.',
    },
    {
      name: 'DEFREAL',
      kind: 'command',
      domain: 'data',
      syntax: 'DEFREAL <letter>[-<letter>]',
      description: 'Default listed initial letters to real type.',
    },
    {
      name: 'DEFSTR',
      kind: 'command',
      domain: 'data',
      syntax: 'DEFSTR <letter>[-<letter>]',
      description: 'Default listed initial letters to string type.',
    },
    {
      name: 'DEG',
      kind: 'command',
      domain: 'numeric',
      syntax: 'DEG',
      description: 'Degrees mode for trigonometry.',
    },
    {
      name: 'DELETE',
      kind: 'command',
      domain: 'program-editing',
      syntax: 'DELETE <line>-<line>',
      description: 'Delete a range of lines (editor command).',
    },
    {
      name: 'DIM',
      kind: 'command',
      domain: 'data',
      syntax: 'DIM <var>(<number>[, <number>]…)',
      description: 'Dimension an array.',
    },
    {
      name: 'DRAW',
      kind: 'command',
      domain: 'graphics',
      syntax: 'DRAW <x>, <y>[, <pen>]',
      description: 'Draw a line to graphics point x,y.',
    },
    {
      name: 'DRAWR',
      kind: 'command',
      domain: 'graphics',
      syntax: 'DRAWR <dx>, <dy>[, <pen>]',
      description: 'Draw a line relative to the graphics cursor.',
    },
    {
      name: 'EDIT',
      kind: 'command',
      domain: 'program-editing',
      syntax: 'EDIT <line>',
      description: 'Edit a program line (editor command).',
    },
    {
      name: 'ELSE',
      kind: 'command',
      domain: 'control-flow',
      syntax: 'IF <number> THEN <statement> ELSE <statement>',
      description: 'Alternative branch of IF…THEN.',
    },
    {
      name: 'END',
      kind: 'command',
      domain: 'control-flow',
      syntax: 'END',
      description: 'End the program.',
    },
    {
      name: 'ENT',
      kind: 'command',
      domain: 'sound',
      syntax: 'ENT <envelope>[, <section>]…',
      description:
        'Defines a tone envelope, numbered 1 to 15, that SOUND can use to sweep a note in pitch. Takes up to five sections, each of a step count, a step size and a pause; a negative envelope number makes the sweep absolute rather than relative.',
    },
    {
      name: 'ENV',
      kind: 'command',
      domain: 'sound',
      syntax: 'ENV <envelope>[, <section>]…',
      description:
        'Defines a volume envelope, numbered 1 to 15, that SOUND can use to shape a note over time. Takes up to five sections, each of a step count, a step size and a pause.',
    },
    {
      name: 'ERASE',
      kind: 'command',
      domain: 'data',
      syntax: 'ERASE <var>[, <var>]…',
      description: 'Erase arrays.',
    },
    {
      name: 'ERROR',
      kind: 'command',
      domain: 'error-handling',
      syntax: 'ERROR <number>',
      description: 'Raise an error.',
    },
    {
      name: 'EVERY',
      kind: 'command',
      domain: 'control-flow',
      syntax: 'EVERY <number>[, <timer>] GOSUB <line>',
      description: 'Call a subroutine repeatedly (1/50s units).',
    },
    {
      name: 'FOR',
      kind: 'command',
      domain: 'control-flow',
      syntax: 'FOR <numvar> = <number> TO <number> [STEP <number>]',
      description: 'Start a counted loop.',
    },
    {
      name: 'GOSUB',
      kind: 'command',
      domain: 'control-flow',
      syntax: 'GOSUB <line>',
      description: 'Call a subroutine by line number.',
    },
    {
      name: 'GOTO',
      kind: 'command',
      domain: 'control-flow',
      syntax: 'GOTO <line>',
      description: 'Jump to a line number.',
    },
    {
      name: 'IF',
      kind: 'command',
      domain: 'control-flow',
      syntax: 'IF <number> THEN <statement> [ELSE <statement>]',
      description: 'Conditional execution.',
    },
    {
      name: 'INK',
      kind: 'command',
      domain: 'colour',
      syntax: 'INK <pen>, <colour>[, <colour>]',
      description: 'Assign a colour to a pen (two colours flash).',
    },
    {
      name: 'INPUT',
      kind: 'command',
      domain: 'input',
      syntax: 'INPUT [#<stream>,] [<prompt>;] <var>[, <var>]…',
      description: 'Read values from the keyboard or a file.',
    },
    {
      name: 'KEY',
      kind: 'command',
      domain: 'input',
      syntax: 'KEY <number>, <string>',
      description: 'Define an expansion (function-key) string.',
    },
    {
      name: 'LET',
      kind: 'command',
      domain: 'data',
      syntax: 'LET <var> = <expr>',
      description: 'Assignment (LET is optional).',
    },
    {
      name: 'LINE',
      kind: 'command',
      domain: 'input',
      syntax: 'LINE INPUT [#<stream>,] <strvar>',
      description: 'LINE INPUT reads a whole line of text.',
    },
    {
      name: 'LIST',
      kind: 'command',
      domain: 'program-editing',
      syntax: 'LIST [<line>-<line>][, #<stream>]',
      description: 'List the program.',
    },
    {
      name: 'LOAD',
      kind: 'command',
      domain: 'storage',
      syntax: 'LOAD <filename>[, <addr>]',
      description: 'Load a program.',
    },
    {
      name: 'LOCATE',
      kind: 'command',
      domain: 'text-screen',
      syntax: 'LOCATE [#<stream>,] <col>, <row>',
      description: 'Move the text cursor.',
    },
    {
      name: 'MEMORY',
      kind: 'command',
      domain: 'memory-hardware',
      syntax: 'MEMORY <addr>',
      description: 'Set the top of BASIC memory (HIMEM).',
    },
    {
      name: 'MERGE',
      kind: 'command',
      domain: 'storage',
      syntax: 'MERGE <filename>',
      description: 'Merge a program from tape/disc.',
    },
    {
      name: 'MID$',
      kind: 'function',
      domain: 'strings',
      syntax: 'MID$(<string>, <start>[, <length>])',
      description: 'Substring (also assignable as a statement).',
    },
    {
      name: 'MODE',
      kind: 'command',
      domain: 'graphics',
      syntax: 'MODE <mode>',
      description: 'Select screen mode 0-2.',
    },
    {
      name: 'MOVE',
      kind: 'command',
      domain: 'graphics',
      syntax: 'MOVE <x>, <y>',
      description: 'Move the graphics cursor.',
    },
    {
      name: 'MOVER',
      kind: 'command',
      domain: 'graphics',
      syntax: 'MOVER <dx>, <dy>',
      description: 'Move the graphics cursor relatively.',
    },
    {
      name: 'NEXT',
      kind: 'command',
      domain: 'control-flow',
      syntax: 'NEXT [<numvar>]',
      description: 'End of a FOR loop.',
    },
    {
      name: 'NEW',
      kind: 'command',
      domain: 'program-editing',
      syntax: 'NEW',
      description: 'Erase the current program.',
    },
    {
      name: 'ON',
      kind: 'command',
      domain: 'control-flow',
      syntax:
        'ON <number> GOTO <line>[, <line>]… | ON <number> GOSUB <line>[, <line>]…',
      description:
        'Jumps to the line at the given position in the list, counting from 1; falls through to the next statement when the value is 0 or past the end of the list.',
    },
    {
      name: 'ON BREAK',
      kind: 'command',
      domain: 'error-handling',
      syntax: 'ON BREAK GOSUB <line>',
      description: 'Trap the ESC (break) key.',
    },
    {
      name: 'ON ERROR GOTO',
      kind: 'command',
      domain: 'error-handling',
      syntax: 'ON ERROR GOTO <line>',
      description: 'Trap runtime errors.',
    },
    {
      name: 'OPENIN',
      kind: 'command',
      domain: 'storage',
      syntax: 'OPENIN <filename>',
      description: 'Open a file for input.',
    },
    {
      name: 'OPENOUT',
      kind: 'command',
      domain: 'storage',
      syntax: 'OPENOUT <filename>',
      description: 'Open a file for output.',
    },
    {
      name: 'ORIGIN',
      kind: 'command',
      domain: 'graphics',
      syntax: 'ORIGIN <x>, <y>[, <left>, <right>, <top>, <bottom>]',
      description: 'Set the graphics origin (and window).',
    },
    {
      name: 'OUT',
      kind: 'command',
      domain: 'memory-hardware',
      syntax: 'OUT <port>, <byte>',
      description: 'Write a byte to an I/O port.',
    },
    {
      name: 'PAPER',
      kind: 'command',
      domain: 'colour',
      syntax: 'PAPER [#<stream>,] <pen>',
      description: 'Set the text background pen.',
    },
    {
      name: 'PEN',
      kind: 'command',
      domain: 'colour',
      syntax: 'PEN [#<stream>,] <pen>',
      description: 'Set the text foreground pen.',
    },
    {
      name: 'PLOT',
      kind: 'command',
      domain: 'graphics',
      syntax: 'PLOT <x>, <y>[, <pen>]',
      description: 'Plot a graphics point.',
    },
    {
      name: 'PLOTR',
      kind: 'command',
      domain: 'graphics',
      syntax: 'PLOTR <dx>, <dy>[, <pen>]',
      description: 'Plot relative to the graphics cursor.',
    },
    {
      name: 'POKE',
      kind: 'command',
      domain: 'memory-hardware',
      syntax: 'POKE <addr>, <byte>',
      description: 'Write a byte of memory.',
    },
    {
      name: 'PRINT',
      kind: 'command',
      domain: 'text-screen',
      syntax: 'PRINT [#<stream>,] [<expr>][;|,]…',
      description: 'Print to the screen or a stream.',
    },
    {
      name: "'",
      kind: 'command',
      domain: 'program-editing',
      syntax: "'",
      description: 'Comment shorthand (same as REM).',
    },
    {
      name: 'RAD',
      kind: 'command',
      domain: 'numeric',
      syntax: 'RAD',
      description: 'Radians mode for trigonometry.',
    },
    {
      name: 'RANDOMIZE',
      kind: 'command',
      domain: 'numeric',
      syntax: 'RANDOMIZE [<number>]',
      description: 'Seed the random number generator.',
    },
    {
      name: 'READ',
      kind: 'command',
      domain: 'data',
      syntax: 'READ <var>[, <var>]…',
      description: 'Read the next DATA item(s).',
    },
    {
      name: 'RELEASE',
      kind: 'command',
      domain: 'sound',
      syntax: 'RELEASE <mask>',
      description: 'Release held sound channels.',
    },
    {
      name: 'REM',
      kind: 'command',
      domain: 'program-editing',
      syntax: 'REM <comment>',
      description: 'Comment line.',
    },
    {
      name: 'RENUM',
      kind: 'command',
      domain: 'program-editing',
      syntax: 'RENUM [<line>][, <line>][, <number>]',
      description: 'Renumber the program.',
    },
    {
      name: 'RESTORE',
      kind: 'command',
      domain: 'data',
      syntax: 'RESTORE [<line>]',
      description: 'Reset the DATA pointer.',
    },
    {
      name: 'RESUME',
      kind: 'command',
      domain: 'error-handling',
      syntax: 'RESUME [<line> | NEXT]',
      description: 'Resume after an error.',
    },
    {
      name: 'RETURN',
      kind: 'command',
      domain: 'control-flow',
      syntax: 'RETURN',
      description: 'Return from a GOSUB.',
    },
    {
      name: 'RUN',
      kind: 'command',
      domain: 'program-editing',
      syntax: 'RUN [<line> | <filename>]',
      description: 'Run the program (or load and run).',
    },
    {
      name: 'SAVE',
      kind: 'command',
      domain: 'storage',
      syntax: 'SAVE <filename>[, <letter>]',
      description: 'Save the program.',
    },
    {
      name: 'SOUND',
      kind: 'command',
      domain: 'sound',
      syntax:
        'SOUND <channel>, <period>[, <duration>[, <volume>[, <volenv>[, <toneenv>[, <noise>]]]]]',
      description: 'Make a sound.',
    },
    {
      name: 'SPEED',
      kind: 'command',
      domain: 'memory-hardware',
      syntax: 'SPEED WRITE <number>',
      description: 'SPEED WRITE / INK / KEY settings.',
    },
    {
      name: 'STOP',
      kind: 'command',
      domain: 'control-flow',
      syntax: 'STOP',
      description: 'Stop with a break report.',
    },
    {
      name: 'SYMBOL',
      kind: 'command',
      domain: 'text-screen',
      syntax: 'SYMBOL <number>, <byte>[, <byte>]…',
      description:
        'Redefines the shape of one character, given its code and up to eight bytes — one per pixel row, most significant bit leftmost. Only characters at or above the SYMBOL AFTER threshold can be redefined.',
    },
    {
      name: 'TAG',
      kind: 'command',
      domain: 'graphics',
      syntax: 'TAG [#<stream>]',
      description: 'Write text at the graphics cursor.',
    },
    {
      name: 'TAGOFF',
      kind: 'command',
      domain: 'graphics',
      syntax: 'TAGOFF [#<stream>]',
      description: 'Return text to the text cursor.',
    },
    {
      name: 'TROFF',
      kind: 'command',
      domain: 'program-editing',
      syntax: 'TROFF',
      description: 'Turn off line tracing.',
    },
    {
      name: 'TRON',
      kind: 'command',
      domain: 'program-editing',
      syntax: 'TRON',
      description: 'Trace line numbers as they execute.',
    },
    {
      name: 'WAIT',
      kind: 'command',
      domain: 'memory-hardware',
      syntax: 'WAIT <port>, <mask>[, <number>]',
      description: 'Wait for an I/O port state.',
    },
    {
      name: 'WEND',
      kind: 'command',
      domain: 'control-flow',
      syntax: 'WEND',
      description: 'End of a WHILE loop.',
    },
    {
      name: 'WHILE',
      kind: 'command',
      domain: 'control-flow',
      syntax: 'WHILE <number>',
      description: 'Loop while a condition holds.',
    },
    {
      name: 'WIDTH',
      kind: 'command',
      domain: 'text-screen',
      syntax: 'WIDTH <number>',
      description: 'Set the printer line width.',
    },
    {
      name: 'WINDOW',
      kind: 'command',
      domain: 'text-screen',
      syntax: 'WINDOW [#<stream>,] <left>, <right>, <top>, <bottom>',
      description: 'Define a text window.',
    },
    {
      name: 'WRITE',
      kind: 'command',
      domain: 'text-screen',
      syntax: 'WRITE [#<stream>,] <expr>[, <expr>]…',
      description: 'Write values to the screen or a file.',
    },
    {
      name: 'ZONE',
      kind: 'command',
      domain: 'text-screen',
      syntax: 'ZONE <number>',
      description: 'Set the print comma-column width.',
    },
    {
      name: 'DI',
      kind: 'command',
      domain: 'memory-hardware',
      syntax: 'DI',
      description: 'Disable timer interrupts.',
    },
    {
      name: 'EI',
      kind: 'command',
      domain: 'memory-hardware',
      syntax: 'EI',
      description: 'Enable timer interrupts.',
    },
    {
      name: 'FILL',
      kind: 'command',
      domain: 'graphics',
      syntax: 'FILL <pen>',
      description: 'Flood-fill from the graphics cursor.',
      tag: 'BASIC 1.1 only',
      onlyOn: ['cpc6128'],
    },
    {
      name: 'GRAPHICS',
      kind: 'command',
      domain: 'graphics',
      syntax: 'GRAPHICS PEN [<pen>][, <number>]',
      description: 'GRAPHICS PEN / PAPER prefix.',
      tag: 'BASIC 1.1 only',
      onlyOn: ['cpc6128'],
    },
    {
      name: 'MASK',
      kind: 'command',
      domain: 'graphics',
      syntax: 'MASK [<mask>][, <number>]',
      description: 'Set the line-drawing dot pattern.',
      tag: 'BASIC 1.1 only',
      onlyOn: ['cpc6128'],
    },
    {
      name: 'FRAME',
      kind: 'command',
      domain: 'graphics',
      syntax: 'FRAME',
      description: 'Wait for a display frame flyback.',
      tag: 'BASIC 1.1 only',
      onlyOn: ['cpc6128'],
    },
    {
      name: 'CURSOR',
      kind: 'command',
      domain: 'text-screen',
      syntax: 'CURSOR [<number>][, <number>]',
      description: 'Switch the text cursor on or off.',
      tag: 'BASIC 1.1 only',
      onlyOn: ['cpc6128'],
    },
    {
      name: 'ERL',
      kind: 'function',
      domain: 'error-handling',
      syntax: 'ERL',
      description: 'Line number of the last error.',
    },
    {
      name: 'FN',
      kind: 'function',
      domain: 'control-flow',
      syntax: 'FN<name>[(<arg>[, <arg>]…)]',
      description: 'Call a user-defined function.',
    },
    {
      name: 'SPC',
      kind: 'function',
      domain: 'text-screen',
      syntax: 'SPC(<number>)',
      description: 'Print n spaces.',
    },
    {
      name: 'STEP',
      kind: 'command',
      domain: 'control-flow',
      syntax: 'FOR <numvar> = <number> TO <number> STEP <number>',
      description: 'Loop increment in FOR.',
    },
    {
      name: 'SWAP',
      kind: 'command',
      domain: 'text-screen',
      syntax: 'WINDOW SWAP <stream>, <stream>',
      description: 'WINDOW SWAP - exchange two streams.',
    },
    {
      name: 'TAB',
      kind: 'function',
      domain: 'text-screen',
      syntax: 'TAB(<col>)',
      description: 'Position the cursor within PRINT.',
    },
    {
      name: 'THEN',
      kind: 'command',
      domain: 'control-flow',
      syntax: 'IF <number> THEN <statement>',
      description: 'Follows the condition in IF.',
    },
    {
      name: 'TO',
      kind: 'command',
      domain: 'control-flow',
      syntax: 'FOR <numvar> = <number> TO <number>',
      description: 'Loop limit in FOR.',
    },
    {
      name: 'USING',
      kind: 'command',
      domain: 'text-screen',
      syntax: 'PRINT USING <string>; <expr>',
      description: 'Format printed values.',
    },
    {
      name: '>',
      kind: 'operator',
      domain: 'numeric',
      syntax: '<number> > <number> | <string> > <string>',
      description: 'Greater than.',
    },
    {
      name: '=',
      kind: 'operator',
      domain: 'numeric',
      syntax: '<var> = <expr> | <expr> = <expr>',
      description: 'Assignment / equality.',
    },
    {
      name: '>=',
      kind: 'operator',
      domain: 'numeric',
      syntax: '<number> >= <number> | <string> >= <string>',
      description: 'Greater than or equal.',
    },
    {
      name: '<',
      kind: 'operator',
      domain: 'numeric',
      syntax: '<number> < <number> | <string> < <string>',
      description: 'Less than.',
    },
    {
      name: '<>',
      kind: 'operator',
      domain: 'numeric',
      syntax: '<number> <> <number> | <string> <> <string>',
      description: 'Not equal.',
    },
    {
      name: '<=',
      kind: 'operator',
      domain: 'numeric',
      syntax: '<number> <= <number> | <string> <= <string>',
      description: 'Less than or equal.',
    },
    {
      name: '+',
      kind: 'operator',
      domain: 'numeric',
      syntax: '<number> + <number> | <string> + <string>',
      description: 'Addition / concatenation.',
    },
    {
      name: '-',
      kind: 'operator',
      domain: 'numeric',
      syntax: '<number> - <number> | -<number>',
      description: 'Subtraction / negation.',
    },
    {
      name: '*',
      kind: 'operator',
      domain: 'numeric',
      syntax: '<number> * <number>',
      description: 'Multiplication.',
    },
    {
      name: '/',
      kind: 'operator',
      domain: 'numeric',
      syntax: '<number> / <number>',
      description: 'Division.',
    },
    {
      name: '^',
      kind: 'operator',
      domain: 'numeric',
      syntax: '<number> ^ <number>',
      description: 'Exponentiation.',
    },
    {
      name: '\\',
      kind: 'operator',
      domain: 'numeric',
      syntax: '<number> \\ <number>',
      description: 'Integer division.',
    },
    {
      name: 'AND',
      kind: 'operator',
      domain: 'numeric',
      syntax: '<number> AND <number>',
      description: 'Bitwise/logical AND.',
    },
    {
      name: 'MOD',
      kind: 'operator',
      domain: 'numeric',
      syntax: '<number> MOD <number>',
      description: 'Integer remainder.',
    },
    {
      name: 'OR',
      kind: 'operator',
      domain: 'numeric',
      syntax: '<number> OR <number>',
      description: 'Bitwise/logical OR.',
    },
    {
      name: 'XOR',
      kind: 'operator',
      domain: 'numeric',
      syntax: '<number> XOR <number>',
      description: 'Bitwise/logical exclusive OR.',
    },
    {
      name: 'NOT',
      kind: 'operator',
      domain: 'numeric',
      syntax: 'NOT <number>',
      description: 'Bitwise/logical NOT.',
    },
    {
      name: 'ABS',
      kind: 'function',
      domain: 'numeric',
      syntax: 'ABS(<number>)',
      description: 'Absolute value.',
    },
    {
      name: 'ASC',
      kind: 'function',
      domain: 'strings',
      syntax: 'ASC(<string>)',
      description: 'Character code of the first character.',
    },
    {
      name: 'ATN',
      kind: 'function',
      domain: 'numeric',
      syntax: 'ATN(<number>)',
      description: 'Arctangent.',
    },
    {
      name: 'CHR$',
      kind: 'function',
      domain: 'strings',
      syntax: 'CHR$(<number>)',
      description: 'Character with code n.',
    },
    {
      name: 'CINT',
      kind: 'function',
      domain: 'numeric',
      syntax: 'CINT(<number>)',
      description: 'Round to a 16-bit integer.',
    },
    {
      name: 'COS',
      kind: 'function',
      domain: 'numeric',
      syntax: 'COS(<number>)',
      description: 'Cosine.',
    },
    {
      name: 'CREAL',
      kind: 'function',
      domain: 'numeric',
      syntax: 'CREAL(<number>)',
      description: 'Convert to a real number.',
    },
    {
      name: 'EXP',
      kind: 'function',
      domain: 'numeric',
      syntax: 'EXP(<number>)',
      description: 'e to the power n.',
    },
    {
      name: 'FIX',
      kind: 'function',
      domain: 'numeric',
      syntax: 'FIX(<number>)',
      description: 'Truncate towards zero.',
    },
    {
      name: 'FRE',
      kind: 'function',
      domain: 'memory-hardware',
      syntax: 'FRE(0) | FRE("")',
      description: 'Free BASIC memory.',
    },
    {
      name: 'INKEY',
      kind: 'function',
      domain: 'input',
      syntax: 'INKEY(<key>)',
      description: 'Test a key by key number (-1 if up).',
    },
    {
      name: 'INP',
      kind: 'function',
      domain: 'memory-hardware',
      syntax: 'INP(<port>)',
      description: 'Read a byte from an I/O port.',
    },
    {
      name: 'INT',
      kind: 'function',
      domain: 'numeric',
      syntax: 'INT(<number>)',
      description: 'Round towards minus infinity.',
    },
    {
      name: 'JOY',
      kind: 'function',
      domain: 'input',
      syntax: 'JOY(<number>)',
      description: 'Read a joystick (bit mask).',
    },
    {
      name: 'LEN',
      kind: 'function',
      domain: 'strings',
      syntax: 'LEN(<string>)',
      description: 'String length.',
    },
    {
      name: 'LOG',
      kind: 'function',
      domain: 'numeric',
      syntax: 'LOG(<number>)',
      description: 'Natural logarithm.',
    },
    {
      name: 'LOG10',
      kind: 'function',
      domain: 'numeric',
      syntax: 'LOG10(<number>)',
      description: 'Base-10 logarithm.',
    },
    {
      name: 'LOWER$',
      kind: 'function',
      domain: 'strings',
      syntax: 'LOWER$(<string>)',
      description: 'Lower-case copy of a string.',
    },
    {
      name: 'PEEK',
      kind: 'function',
      domain: 'memory-hardware',
      syntax: 'PEEK(<addr>)',
      description: 'Read a byte of memory.',
    },
    {
      name: 'REMAIN',
      kind: 'function',
      domain: 'control-flow',
      syntax: 'REMAIN(<timer>)',
      description: 'Read and disable a delay timer.',
    },
    {
      name: 'SGN',
      kind: 'function',
      domain: 'numeric',
      syntax: 'SGN(<number>)',
      description: 'Sign of n (-1, 0, 1).',
    },
    {
      name: 'SIN',
      kind: 'function',
      domain: 'numeric',
      syntax: 'SIN(<number>)',
      description: 'Sine.',
    },
    {
      name: 'SPACE$',
      kind: 'function',
      domain: 'strings',
      syntax: 'SPACE$(<number>)',
      description: 'A string of n spaces.',
    },
    {
      name: 'SQ',
      kind: 'function',
      domain: 'sound',
      syntax: 'SQ(<channel>)',
      description: 'Sound-queue state of a channel.',
    },
    {
      name: 'SQR',
      kind: 'function',
      domain: 'numeric',
      syntax: 'SQR(<number>)',
      description: 'Square root.',
    },
    {
      name: 'STR$',
      kind: 'function',
      domain: 'strings',
      syntax: 'STR$(<number>)',
      description: 'Number as a string.',
    },
    {
      name: 'TAN',
      kind: 'function',
      domain: 'numeric',
      syntax: 'TAN(<number>)',
      description: 'Tangent.',
    },
    {
      name: 'UNT',
      kind: 'function',
      domain: 'memory-hardware',
      syntax: 'UNT(<addr>)',
      description: 'Address as a signed integer.',
    },
    {
      name: 'UPPER$',
      kind: 'function',
      domain: 'strings',
      syntax: 'UPPER$(<string>)',
      description: 'Upper-case copy of a string.',
    },
    {
      name: 'VAL',
      kind: 'function',
      domain: 'strings',
      syntax: 'VAL(<string>)',
      description: 'Numeric value of a string.',
    },
    {
      name: 'EOF',
      kind: 'function',
      domain: 'storage',
      syntax: 'EOF',
      description: 'True at end of the input file.',
    },
    {
      name: 'ERR',
      kind: 'function',
      domain: 'error-handling',
      syntax: 'ERR',
      description: 'Error number of the last error.',
    },
    {
      name: 'HIMEM',
      kind: 'function',
      domain: 'memory-hardware',
      syntax: 'HIMEM',
      description: 'Top of BASIC memory.',
    },
    {
      name: 'INKEY$',
      kind: 'function',
      domain: 'input',
      syntax: 'INKEY$',
      description: 'Read a key as a string ("" if none).',
    },
    {
      name: 'PI',
      kind: 'function',
      domain: 'numeric',
      syntax: 'PI',
      description: 'The constant π.',
    },
    {
      name: 'RND',
      kind: 'function',
      domain: 'numeric',
      syntax: 'RND[(<number>)]',
      description: 'Random number 0..1.',
    },
    {
      name: 'TIME',
      kind: 'function',
      domain: 'control-flow',
      syntax: 'TIME',
      description: 'Elapsed time (1/300s units).',
    },
    {
      name: 'XPOS',
      kind: 'function',
      domain: 'graphics',
      syntax: 'XPOS',
      description: 'Graphics cursor x position.',
    },
    {
      name: 'YPOS',
      kind: 'function',
      domain: 'graphics',
      syntax: 'YPOS',
      description: 'Graphics cursor y position.',
    },
    {
      name: 'DERR',
      kind: 'function',
      domain: 'error-handling',
      syntax: 'DERR',
      description: 'Disc error number of the last error.',
      tag: 'BASIC 1.1 only',
      onlyOn: ['cpc6128'],
    },
    {
      name: 'BIN$',
      kind: 'function',
      domain: 'strings',
      syntax: 'BIN$(<number>[, <number>])',
      description: 'Number as a binary string.',
    },
    {
      name: 'DEC$',
      kind: 'function',
      domain: 'strings',
      syntax: 'DEC$(<number>, <string>)',
      description: 'Number formatted to a template.',
      tag: 'BASIC 1.1 only',
      onlyOn: ['cpc6128'],
    },
    {
      name: 'HEX$',
      kind: 'function',
      domain: 'strings',
      syntax: 'HEX$(<number>[, <number>])',
      description: 'Number as a hex string.',
    },
    {
      name: 'INSTR',
      kind: 'function',
      domain: 'strings',
      syntax: 'INSTR([<start>,] <string>, <string>)',
      description: 'Find b$ within a$.',
    },
    {
      name: 'LEFT$',
      kind: 'function',
      domain: 'strings',
      syntax: 'LEFT$(<string>, <length>)',
      description: 'Leftmost n characters.',
    },
    {
      name: 'MAX',
      kind: 'function',
      domain: 'numeric',
      syntax: 'MAX(<number>[, <number>]…)',
      description: 'Largest of its arguments.',
    },
    {
      name: 'MIN',
      kind: 'function',
      domain: 'numeric',
      syntax: 'MIN(<number>[, <number>]…)',
      description: 'Smallest of its arguments.',
    },
    {
      name: 'POS',
      kind: 'function',
      domain: 'text-screen',
      syntax: 'POS(#<stream>)',
      description: 'Text cursor column.',
    },
    {
      name: 'RIGHT$',
      kind: 'function',
      domain: 'strings',
      syntax: 'RIGHT$(<string>, <length>)',
      description: 'Rightmost n characters.',
    },
    {
      name: 'ROUND',
      kind: 'function',
      domain: 'numeric',
      syntax: 'ROUND(<number>[, <number>])',
      description: 'Round to a number of decimals.',
    },
    {
      name: 'STRING$',
      kind: 'function',
      domain: 'strings',
      syntax: 'STRING$(<length>, <number> | <string>)',
      description: 'A character repeated n times.',
    },
    {
      name: 'TEST',
      kind: 'function',
      domain: 'graphics',
      syntax: 'TEST(<x>, <y>)',
      description: 'Ink at graphics point x,y.',
    },
    {
      name: 'TESTR',
      kind: 'function',
      domain: 'graphics',
      syntax: 'TESTR(<dx>, <dy>)',
      description: 'Ink at a relative graphics point.',
    },
    {
      name: 'COPYCHR$',
      kind: 'function',
      domain: 'text-screen',
      syntax: 'COPYCHR$(#<stream>)',
      description: 'Character under the text cursor.',
      tag: 'BASIC 1.1 only',
      onlyOn: ['cpc6128'],
    },
    {
      name: 'VPOS',
      kind: 'function',
      domain: 'text-screen',
      syntax: 'VPOS(#<stream>)',
      description: 'Text cursor row.',
    },
    {
      name: 'SYMBOL AFTER',
      kind: 'command',
      domain: 'text-screen',
      syntax: 'SYMBOL AFTER <number>',
      description: 'Reserve memory for redefined characters.',
    },
    {
      name: 'SPEED WRITE',
      kind: 'command',
      domain: 'storage',
      syntax: 'SPEED WRITE <number>',
      description: 'Set the cassette write speed (0 or 1).',
    },
    {
      name: 'SPEED INK',
      kind: 'command',
      domain: 'colour',
      syntax: 'SPEED INK <number>, <number>',
      description: 'Set the flash rate of flashing colours.',
    },
    {
      name: 'SPEED KEY',
      kind: 'command',
      domain: 'input',
      syntax: 'SPEED KEY <number>, <number>',
      description: 'Set the keyboard auto-repeat rates.',
    },
    {
      name: 'KEY DEF',
      kind: 'command',
      domain: 'input',
      syntax: 'KEY DEF <key>, <number>[, <number>[, <number>[, <number>]]]',
      description: 'Redefine a key of the keyboard.',
    },
    {
      name: 'LINE INPUT',
      kind: 'command',
      domain: 'input',
      syntax: 'LINE INPUT [#<stream>,] <strvar>',
      description: 'Read a whole line of text.',
    },
    {
      name: 'CHAIN MERGE',
      kind: 'command',
      domain: 'storage',
      syntax: 'CHAIN MERGE <filename>[, <line>]',
      description: 'Load and merge another program, then run.',
    },
    {
      name: 'ON BREAK GOSUB',
      kind: 'command',
      domain: 'error-handling',
      syntax: 'ON BREAK GOSUB <line>',
      description: 'Call a subroutine when ESC breaks.',
    },
    {
      name: 'ON BREAK STOP',
      kind: 'command',
      domain: 'error-handling',
      syntax: 'ON BREAK STOP',
      description: 'Restore normal ESC (break) handling.',
    },
    {
      name: 'WINDOW SWAP',
      kind: 'command',
      domain: 'text-screen',
      syntax: 'WINDOW SWAP <stream>, <stream>',
      description: 'Exchange two text streams.',
    },
    {
      name: 'CLEAR INPUT',
      kind: 'command',
      domain: 'input',
      syntax: 'CLEAR INPUT',
      description: 'Discard pending keyboard input.',
      tag: 'BASIC 1.1 only',
      onlyOn: ['cpc6128'],
    },
    {
      name: 'GRAPHICS PEN',
      kind: 'command',
      domain: 'colour',
      syntax: 'GRAPHICS PEN [<pen>][, <number>]',
      description: 'Set the graphics drawing ink.',
      tag: 'BASIC 1.1 only',
      onlyOn: ['cpc6128'],
    },
    {
      name: 'GRAPHICS PAPER',
      kind: 'command',
      domain: 'colour',
      syntax: 'GRAPHICS PAPER <pen>',
      description: 'Set the graphics background ink.',
      tag: 'BASIC 1.1 only',
      onlyOn: ['cpc6128'],
    },
    {
      name: 'ON BREAK CONT',
      kind: 'command',
      domain: 'error-handling',
      syntax: 'ON BREAK CONT',
      description: 'Ignore the ESC (break) key.',
      tag: 'BASIC 1.1 only',
      onlyOn: ['cpc6128'],
    },
  ],
};
