import Z80 from '../../../emulator/z80/z80core.js';
import type { Z80Core } from '../../../emulator/z80/z80core.js';
import type { MachineEmulator } from '../../types';
import { Zx80Memory } from './memory';
import { Zx81Keyboard } from '../../zx81/emulator/keyboard';
import { renderDisplay, DISPLAY_WIDTH, DISPLAY_HEIGHT } from './display';
import {
  SYSVARS_BASE,
  E_LINE,
  D_FILE,
  DF_END,
  ROM_LOAD_TRAP,
  ROM_POST_LOAD,
} from '../sysvars';

const TSTATES_PER_FRAME = 65000; // ~3.25MHz / 50Hz
const MAX_BOOT_FRAMES = 600;
/** Inverse-cursor character the editor shows on the empty edit line once ready. */
const EDIT_CURSOR = 0xb0;

/**
 * The Sinclair ZX80: Z80 + 4K ROM + RAM + the minimal hardware the unmodified
 * ROM needs.
 *
 * The ZX80 is essentially the ZX81 in FAST mode only: it has no NMI generator
 * and no SLOW (compute-and-display) mode, so the screen is blank while a
 * program computes and the picture is regenerated by the CPU between lines.
 * That means this machine is the ZX81 wiring minus the NMI generator:
 *
 *  - Echoed memory at 0x8000+ where M1 opcode fetches of bytes with bit 6
 *    clear execute as NOP (the ROM "executes" the display file this way).
 *  - The maskable interrupt wired to A6 of the refresh address: fires when the
 *    R register's bit 6 goes low while interrupts are enabled.
 *  - Keyboard matrix on IN (0xFE) — identical to the ZX81, so the ZX81's
 *    keyboard implementation is reused directly.
 *
 * Video is a per-frame D_FILE snapshot (see display.ts).
 */
export class Zx80Machine implements MachineEmulator {
  readonly displayWidth = DISPLAY_WIDTH;
  readonly displayHeight = DISPLAY_HEIGHT;

  private readonly memory: Zx80Memory;
  private readonly keyboard = new Zx81Keyboard();
  private readonly cpu: Z80Core;
  private prevRBit6 = true;
  private speed = 1;
  private imageData: ImageData | null = null;
  private disposed = false;
  /** `.O` image waiting to be injected when the ROM reaches its LOAD loop. */
  private pendingImage: Uint8Array | null = null;

  constructor(opts: { rom: Uint8Array; ramKb: 16 | 32 | 64 }) {
    this.memory = new Zx80Memory(opts.rom, opts.ramKb);
    this.cpu = Z80({
      mem_read: this.memory.read,
      mem_write: this.memory.write,
      io_read: (port: number) => {
        if ((port & 0x01) === 0) {
          return this.keyboard.readPort((port >> 8) & 0xff);
        }
        return 0xff;
      },
      io_write: () => {
        // The ZX80 has no NMI generator to toggle; OUTs only end the vsync
        // pulse on real hardware, which the snapshot renderer doesn't model.
      },
      opcode_read: (address: number) => {
        const b = this.memory.read(address);
        if (address >= 0x8000 && (b & 0x40) === 0) return 0x00;
        return b;
      },
    });
    this.cpu.reset();
  }

  reset(): void {
    this.memory.ram.fill(0);
    this.keyboard.releaseAll();
    this.prevRBit6 = true;
    this.cpu.reset();
  }

  runFrame(): void {
    const budget = TSTATES_PER_FRAME * this.speed;
    let cycles = 0;
    while (cycles < budget) {
      // Flash-load trap: when LOAD sits in its tape leader-detection loop,
      // drop the queued .O image into RAM at 0x4000 and continue at the same
      // place a real tape LOAD hands control back (0x0283) — which rebuilds
      // the edit line and display file from the loaded system variables.
      if (this.pendingImage && this.cpu.getPC() === ROM_LOAD_TRAP) {
        const image = this.pendingImage;
        this.pendingImage = null;
        for (let i = 0; i < image.length; i++) {
          this.memory.write(SYSVARS_BASE + i, image[i]!);
        }
        this.keyboard.releaseAll();
        this.cpu.setPC(ROM_POST_LOAD);
      }
      let t: number;
      if (this.cpu.isHalted()) {
        const r = this.cpu.getR();
        this.cpu.setR((r & 0x80) | ((r + 1) & 0x7f));
        t = 4;
      } else {
        t = this.cpu.run_instruction();
      }
      cycles += t;

      // Maskable INT on falling edge of R bit 6 (refresh address line A6).
      const rBit6 = (this.cpu.getR() & 0x40) !== 0;
      if (this.prevRBit6 && !rBit6 && this.cpu.getIFF1()) {
        this.cpu.interrupt(false, 0xff);
      }
      this.prevRBit6 = rBit6;
    }
  }

  /**
   * Run whole frames until the ROM has booted to the empty edit cursor, then a
   * few more so the keyboard scan is live — the cursor appears ~15 frames in
   * but the editor does not capture keystrokes reliably until a little later.
   */
  private bootToReady(): void {
    for (let frame = 0; frame < MAX_BOOT_FRAMES; frame++) {
      this.runFrame();
      if (
        frame >= 10 &&
        this.memory.read(this.memory.readWord(E_LINE)) === EDIT_CURSOR
      ) {
        for (let settle = 0; settle < 40; settle++) this.runFrame();
        return;
      }
    }
    throw new Error('ZX80 ROM did not boot — emulator bug');
  }

  /** Hold a key chord for a few frames, then release it. */
  private tapKeys(codes: string[]): void {
    for (const c of codes) this.keyboard.setKey(c, true);
    for (let i = 0; i < 6; i++) this.runFrame();
    for (const c of codes) this.keyboard.setKey(c, false);
    for (let i = 0; i < 8; i++) this.runFrame();
  }

  loadProgram(image: Uint8Array): void {
    this.reset();
    this.bootToReady();
    // Queue the image, then type LOAD + NEW LINE. When the ROM reaches its
    // tape leader-detection loop the trap in runFrame() injects the image —
    // the authentic load path, the same one a real cassette would drive.
    this.pendingImage = image;
    this.tapKeys(['KeyW']); // LOAD (keyword key in K mode)
    this.tapKeys(['Enter']);
    for (let i = 0; i < 200 && this.pendingImage; i++) this.runFrame();
    if (this.pendingImage) {
      this.pendingImage = null;
      throw new Error('ZX80 ROM never reached the LOAD trap');
    }
    // The ZX80 (unlike the ZX81) does not auto-run a freshly loaded program,
    // so type RUN + NEW LINE to start it — the same thing a user would do.
    this.tapKeys(['KeyR']); // RUN
    this.tapKeys(['Enter']);
  }

  renderTo(ctx: CanvasRenderingContext2D): void {
    if (!this.imageData) {
      this.imageData = ctx.createImageData(DISPLAY_WIDTH, DISPLAY_HEIGHT);
    }
    renderDisplay(
      this.memory,
      this.memory.readWord(D_FILE),
      this.memory.readWord(DF_END),
      this.imageData.data,
    );
    ctx.putImageData(this.imageData, 0, 0);
  }

  /** Direct access for tests and debugging. */
  get mem(): Zx80Memory {
    return this.memory;
  }

  get processor(): Z80Core {
    return this.cpu;
  }

  keyEvent(e: KeyboardEvent, down: boolean): boolean {
    return this.keyboard.handleKey(e, down);
  }

  setKey(token: string, down: boolean): void {
    this.keyboard.setKey(token, down);
  }

  releaseAllKeys(): void {
    this.keyboard.releaseAll();
  }

  setSpeed(multiplier: number): void {
    this.speed = Math.max(0.1, multiplier);
  }

  dispose(): void {
    if (this.disposed) return;
    this.disposed = true;
    this.keyboard.releaseAll();
    // Drop the frame buffer and any queued load so they are freed at once
    // rather than waiting on GC of the whole machine.
    this.imageData = null;
    this.pendingImage = null;
  }
}
