import Z80 from '../../../emulator/z80/z80core.js';
import type { Z80Core } from '../../../emulator/z80/z80core.js';
import type { MachineEmulator } from '../../types';
import { Zx80Memory } from './memory';
import { Zx81Keyboard } from '../../zx81/emulator/keyboard';
import { renderDisplay, DISPLAY_WIDTH, DISPLAY_HEIGHT } from './display';
import { D_FILE } from '../sysvars';

const TSTATES_PER_FRAME = 65000; // ~3.25MHz / 50Hz

/**
 * The Sinclair ZX80: Z80 + 4K ROM + RAM + the minimal hardware the unmodified
 * ROM needs.
 *
 * The ZX80 is essentially the ZX81 in FAST mode only: it has no NMI generator
 * and no SLOW (compute-and-display) mode, so the screen is blank while a
 * program computes and the picture is regenerated by the CPU between lines.
 * That means this machine is the ZX81 wiring minus the NMI generator:
 *
 *  - Echoed memory at 0x8000+ where M1 opcode fetches of bytes with bit 6
 *    clear execute as NOP (the ROM "executes" the display file this way).
 *  - The maskable interrupt wired to A6 of the refresh address: fires when the
 *    R register's bit 6 goes low while interrupts are enabled.
 *  - Keyboard matrix on IN (0xFE) — identical to the ZX81, so the ZX81's
 *    keyboard implementation is reused directly.
 *
 * Video is a per-frame D_FILE snapshot (see display.ts).
 */
export class Zx80Machine implements MachineEmulator {
  readonly displayWidth = DISPLAY_WIDTH;
  readonly displayHeight = DISPLAY_HEIGHT;

  private readonly memory: Zx80Memory;
  private readonly keyboard = new Zx81Keyboard();
  private readonly cpu: Z80Core;
  private prevRBit6 = true;
  private speed = 1;
  private imageData: ImageData | null = null;
  private disposed = false;

  constructor(opts: { rom: Uint8Array; ramKb: 16 | 32 | 64 }) {
    this.memory = new Zx80Memory(opts.rom, opts.ramKb);
    this.cpu = Z80({
      mem_read: this.memory.read,
      mem_write: this.memory.write,
      io_read: (port: number) => {
        if ((port & 0x01) === 0) {
          return this.keyboard.readPort((port >> 8) & 0xff);
        }
        return 0xff;
      },
      io_write: () => {
        // The ZX80 has no NMI generator to toggle; OUTs only end the vsync
        // pulse on real hardware, which the snapshot renderer doesn't model.
      },
      opcode_read: (address: number) => {
        const b = this.memory.read(address);
        if (address >= 0x8000 && (b & 0x40) === 0) return 0x00;
        return b;
      },
    });
    this.cpu.reset();
  }

  reset(): void {
    this.memory.ram.fill(0);
    this.keyboard.releaseAll();
    this.prevRBit6 = true;
    this.cpu.reset();
  }

  runFrame(): void {
    const budget = TSTATES_PER_FRAME * this.speed;
    let cycles = 0;
    while (cycles < budget) {
      let t: number;
      if (this.cpu.isHalted()) {
        const r = this.cpu.getR();
        this.cpu.setR((r & 0x80) | ((r + 1) & 0x7f));
        t = 4;
      } else {
        t = this.cpu.run_instruction();
      }
      cycles += t;

      // Maskable INT on falling edge of R bit 6 (refresh address line A6).
      const rBit6 = (this.cpu.getR() & 0x40) !== 0;
      if (this.prevRBit6 && !rBit6 && this.cpu.getIFF1()) {
        this.cpu.interrupt(false, 0xff);
      }
      this.prevRBit6 = rBit6;
    }
  }

  loadProgram(_image: Uint8Array): void {
    // FOUNDATION ONLY: this machine boots the real ZX80 ROM and renders its
    // display, but program injection is not yet wired. Unlike the ZX81 — which
    // has a documented tape-LOAD trap and inline floating-point literals — the
    // ZX80's load/run entry points and its software-timed keyboard editor still
    // need mapping against a ROM disassembly before a .O image can be injected
    // and auto-run. Tracked in docs/dialect-roadmap.md.
    void _image;
  }

  renderTo(ctx: CanvasRenderingContext2D): void {
    if (!this.imageData) {
      this.imageData = ctx.createImageData(DISPLAY_WIDTH, DISPLAY_HEIGHT);
    }
    renderDisplay(
      this.memory,
      this.memory.readWord(D_FILE),
      this.imageData.data,
    );
    ctx.putImageData(this.imageData, 0, 0);
  }

  /** Direct access for tests and debugging. */
  get mem(): Zx80Memory {
    return this.memory;
  }

  get processor(): Z80Core {
    return this.cpu;
  }

  keyEvent(e: KeyboardEvent, down: boolean): boolean {
    return this.keyboard.handleKey(e, down);
  }

  setKey(token: string, down: boolean): void {
    this.keyboard.setKey(token, down);
  }

  releaseAllKeys(): void {
    this.keyboard.releaseAll();
  }

  setSpeed(multiplier: number): void {
    this.speed = Math.max(0.1, multiplier);
  }

  dispose(): void {
    if (this.disposed) return;
    this.disposed = true;
    this.keyboard.releaseAll();
  }
}
