import Z80 from '../../../emulator/z80/z80core.js';
import type { Z80Core } from '../../../emulator/z80/z80core.js';
import type {
  DebugStepOptions,
  DebugStepResult,
  MachineEmulator,
  MachineMemoryStats,
  MachineScreenText,
  LineCost,
} from '../../types';
import { Zx80Memory } from './memory';
import {
  LineCostRecorder,
  PROFILE_SLICE_CYCLES,
} from '../../../emulator/lineCostRecorder';
import { ProgramEndLatch } from '../../../emulator/programEndLatch';
import { createMachineLoop } from '../../../emulator/machineLoop';
import { NEWLINE, zx80Charset } from '../charset';
import { readSinclairScreenText } from '../../sinclairScreenText';
import { Zx81Keyboard } from '../../zx81/emulator/keyboard';
import { renderDisplay, DISPLAY_WIDTH, DISPLAY_HEIGHT } from './display';
import {
  SYSVARS_BASE,
  PPC,
  E_LINE,
  D_FILE,
  DF_END,
  ROM_LOAD_TRAP,
  ROM_POST_LOAD,
  ROM_PROGRAM_END,
} from '../sysvars';

const CPU_HZ = 3_250_000;
const TSTATES_PER_LINE = 208; // one 64µs TV scanline at 3.25MHz
/**
 * A PAL field: 312 scanlines. Like the ZX81 the ZX80 has no frame hardware -
 * the ROM builds the picture between keystrokes and the screen goes blank while
 * a program runs - so this is the host's render slice, not a machine cycle.
 */
const TSTATES_PER_FRAME = TSTATES_PER_LINE * 312; // 64896 → ~50.08Hz
const MAX_BOOT_FRAMES = 600;
/** Inverse-cursor character the editor shows on the empty edit line once ready. */
const EDIT_CURSOR = 0xb0;

/**
 * The Sinclair ZX80: Z80 + 4K ROM + RAM + the minimal hardware the unmodified
 * ROM needs.
 *
 * The ZX80 is essentially the ZX81 in FAST mode only: it has no NMI generator
 * and no SLOW (compute-and-display) mode, so the screen is blank while a
 * program computes and the picture is regenerated by the CPU between lines.
 * That means this machine is the ZX81 wiring minus the NMI generator:
 *
 *  - Echoed memory at 0x8000+ where M1 opcode fetches of bytes with bit 6
 *    clear execute as NOP (the ROM "executes" the display file this way).
 *  - The maskable interrupt wired to A6 of the refresh address: fires when the
 *    R register's bit 6 goes low while interrupts are enabled.
 *  - Keyboard matrix on IN (0xFE) - identical to the ZX81, so the ZX81's
 *    keyboard implementation is reused directly.
 *
 * Video is a per-frame D_FILE snapshot (see display.ts).
 */
export class Zx80Machine implements MachineEmulator {
  readonly displayWidth = DISPLAY_WIDTH;
  readonly displayHeight = DISPLAY_HEIGHT;
  readonly frameHz = CPU_HZ / TSTATES_PER_FRAME;

  private readonly memory: Zx80Memory;
  private readonly keyboard = new Zx81Keyboard();
  private readonly cpu: Z80Core;
  private prevRBit6 = true;
  /**
   * Per-BASIC-line cost recorder for the profiler. Off by default; the run loop
   * arms it for the life of a run, and {@link stepInstruction} charges the
   * T-states it consumes to the line executing at the time. The reader charges memory the same way:
   * the machine's in-use figure is read at each change of line, and what it
   * rose by is charged to the line that has just stopped executing.
   */
  private readonly profile = new LineCostRecorder(
    PROFILE_SLICE_CYCLES,
    () => this.readMemoryStats()?.used ?? null,
  );

  /** Frame and debug slice, from one walk over the budget. */
  private readonly loop = createMachineLoop({
    cyclesPerFrame: TSTATES_PER_FRAME,
    step: () => this.stepInstruction(),
    currentLine: () => this.currentLine(),
  });
  private imageData: ImageData | null = null;
  private disposed = false;
  /** `.O` image waiting to be injected when the ROM reaches its LOAD loop. */
  private pendingImage: Uint8Array | null = null;
  /** Run state, latched when the ROM reaches {@link ROM_PROGRAM_END}. */
  private readonly runLatch = new ProgramEndLatch();

  constructor(opts: { rom: Uint8Array; ramKb: 16 | 32 | 64 }) {
    this.memory = new Zx80Memory(opts.rom, opts.ramKb);
    this.cpu = Z80({
      mem_read: this.memory.read,
      mem_write: this.memory.write,
      io_read: (port: number) => {
        if ((port & 0x01) === 0) {
          return this.keyboard.readPort((port >> 8) & 0xff);
        }
        return 0xff;
      },
      io_write: () => {
        // The ZX80 has no NMI generator to toggle; OUTs only end the vsync
        // pulse on real hardware, which the snapshot renderer doesn't model.
      },
      opcode_read: (address: number) => {
        const b = this.memory.read(address);
        if (address >= 0x8000 && (b & 0x40) === 0) return 0x00;
        return b;
      },
    });
    this.cpu.reset();
  }

  reset(): void {
    this.memory.ram.fill(0);
    this.keyboard.releaseAll();
    this.prevRBit6 = true;
    this.runLatch.clear();
    this.cpu.reset();
  }

  /**
   * One CPU step plus the ZX80's per-instruction housekeeping (flash-load trap,
   * halted-refresh handling, maskable INT on R bit-6 falling edge). Returns the
   * T-states consumed. This is the machine loop's step, so a frame and a debug
   * slice run identical instructions.
   */
  private stepInstruction(): number {
    // Flash-load trap: when LOAD sits in its tape leader-detection loop,
    // drop the queued .O image into RAM at 0x4000 and continue at the same
    // place a real tape LOAD hands control back (0x0283) - which rebuilds
    // the edit line and display file from the loaded system variables.
    if (this.pendingImage && this.cpu.getPC() === ROM_LOAD_TRAP) {
      const image = this.pendingImage;
      this.pendingImage = null;
      for (let i = 0; i < image.length; i++) {
        this.memory.write(SYSVARS_BASE + i, image[i]!);
      }
      this.keyboard.releaseAll();
      this.cpu.setPC(ROM_POST_LOAD);
    }
    // The interpreter has given up on the program (see ROM_PROGRAM_END): latch
    // it, so isProgramRunning() has an answer this ROM records nowhere else.
    if (this.cpu.getPC() === ROM_PROGRAM_END) this.runLatch.stopped();
    let t: number;
    if (this.cpu.isHalted()) {
      const r = this.cpu.getR();
      this.cpu.setR((r & 0x80) | ((r + 1) & 0x7f));
      t = 4;
    } else {
      t = this.cpu.run_instruction();
    }

    // Maskable INT on falling edge of R bit 6 (refresh address line A6).
    const rBit6 = (this.cpu.getR() & 0x40) !== 0;
    if (this.prevRBit6 && !rBit6 && this.cpu.getIFF1()) {
      this.cpu.interrupt(false, 0xff);
    }
    this.prevRBit6 = rBit6;

    // Charge the T-states to the BASIC line executing them. Here rather than in
    // debugStep because a run the IDE performs to check an assistant answer
    // deliberately opens no debug session, and would otherwise go unmeasured.
    const p = this.profile;
    if (p.enabled) {
      p.pending += t;
      if (p.pending >= p.slice) p.sample(this.currentLine());
    }
    return t;
  }

  runFrame(): void {
    this.loop.runFrame();
  }

  /**
   * The BASIC line currently being executed, read from PPC (which on the ZX80
   * holds the line number directly). Returns null when it isn't a valid program
   * line (e.g. while editing, before a RUN, or after the program ends).
   */
  currentLine(): number | null {
    const lineNo = this.memory.rawReadWord(PPC);
    return lineNo >= 1 && lineNo <= 9999 ? lineNo : null;
  }

  /**
   * Whether BASIC is executing a program, from the latch rather than from a
   * system variable: no ZX80 system variable separates a running program from a
   * finished one (see {@link ROM_PROGRAM_END}), but the ROM address at which the
   * interpreter gives up does. Running is promoted from PPC, so the frames spent
   * loading and typing RUN are reported as "not answerable yet".
   */
  isProgramRunning(): boolean | null {
    if (this.disposed) return null;
    return this.runLatch.read(this.currentLine() !== null);
  }

  debugStep(opts: DebugStepOptions): DebugStepResult {
    return this.loop.debugStep(opts);
  }

  /**
   * Run whole frames until the ROM has booted to the empty edit cursor, then a
   * few more so the keyboard scan is live - the cursor appears ~15 frames in
   * but the editor does not capture keystrokes reliably until a little later.
   */
  private bootToReady(): void {
    for (let frame = 0; frame < MAX_BOOT_FRAMES; frame++) {
      this.runFrame();
      if (
        frame >= 10 &&
        this.memory.read(this.memory.readWord(E_LINE)) === EDIT_CURSOR
      ) {
        for (let settle = 0; settle < 40; settle++) this.runFrame();
        return;
      }
    }
    throw new Error('ZX80 ROM did not boot - emulator bug');
  }

  /** Hold a key chord for a few frames, then release it. */
  private tapKeys(codes: string[]): void {
    for (const c of codes) this.keyboard.setKey(c, true);
    for (let i = 0; i < 6; i++) this.runFrame();
    for (const c of codes) this.keyboard.setKey(c, false);
    for (let i = 0; i < 8; i++) this.runFrame();
  }

  loadProgram(image: Uint8Array): void {
    this.reset();
    this.bootToReady();
    // Arm the run latch for everything below: neither booting nor the LOAD nor
    // the RUN keystrokes reach ROM_PROGRAM_END, so the next sighting of it is
    // the program this load starts ending - which for a one-line program is
    // inside the frames the RUN's NEW LINE pumps.
    this.runLatch.arm();
    // Queue the image, then type LOAD + NEW LINE. When the ROM reaches its
    // tape leader-detection loop the trap in runFrame() injects the image -
    // the authentic load path, the same one a real cassette would drive.
    // Machine code and data ride inside this image as hidden `#BIN` REM records
    // (see `src/app/listingBlocks.ts`), so there is nothing to inject separately.
    this.pendingImage = image;
    this.tapKeys(['KeyW']); // LOAD (keyword key in K mode)
    this.tapKeys(['Enter']);
    for (let i = 0; i < 200 && this.pendingImage; i++) this.runFrame();
    if (this.pendingImage) {
      this.pendingImage = null;
      throw new Error('ZX80 ROM never reached the LOAD trap');
    }
    // The ZX80 (unlike the ZX81) does not auto-run a freshly loaded program,
    // so type RUN + NEW LINE to start it - the same thing a user would do.
    this.tapKeys(['KeyR']); // RUN
    this.tapKeys(['Enter']);
  }

  renderTo(ctx: CanvasRenderingContext2D): void {
    if (!this.imageData) {
      this.imageData = ctx.createImageData(DISPLAY_WIDTH, DISPLAY_HEIGHT);
    }
    renderDisplay(
      this.memory,
      this.memory.readWord(D_FILE),
      this.memory.readWord(DF_END),
      this.imageData.data,
    );
    ctx.putImageData(this.imageData, 0, 0);
  }

  /**
   * The display file as 32x24 characters, through the shared Sinclair walk -
   * the ZX80's display file has the same variable-length, NEWLINE-terminated
   * shape as the ZX81's, and collapses the same way when RAM is short.
   */
  readScreenText(): MachineScreenText | null {
    return readSinclairScreenText({
      read: (a) => this.memory.read(a),
      dfile: this.memory.readWord(D_FILE),
      charset: zx80Charset,
      newline: NEWLINE,
    });
  }

  /** Direct access for tests and debugging. */
  get mem(): Zx80Memory {
    return this.memory;
  }

  get processor(): Z80Core {
    return this.cpu;
  }

  /**
   * Actual RAM figures from the ROM's own pointers. The ZX80 stacks its
   * dynamic areas as sysvars → program → variables → edit line → display
   * file, so DF_END (the end of the display file) is the top of everything in
   * use; above it to the top of the RAM pack is spare (the machine stack grows
   * down from there, as on real hardware).
   */
  readMemoryStats(): MachineMemoryStats | null {
    // The echo region mirrors the lower 32K, so addressable RAM caps at 0x8000
    // regardless of pack size.
    const ramTop = 0x4000 + Math.min(this.memory.ram.length, 0x4000);
    const dfEnd = this.memory.readWord(DF_END);
    const used = dfEnd - SYSVARS_BASE;
    const free = ramTop - dfEnd;
    // Implausible pointers mean the ROM hasn't initialised them yet.
    if (dfEnd <= SYSVARS_BASE || used <= 0 || free < 0) return null;
    return { used, free };
  }

  setProfileRecording(enabled: boolean): void {
    this.profile.setEnabled(enabled);
  }

  drainProfile(): LineCost[] | null {
    return this.profile.drain();
  }

  setMemoryActivityRecording(enabled: boolean): void {
    this.memory.activity.enabled = enabled;
    // Drop any hits accumulated in a previous session so a reopened overlay
    // starts clean rather than flashing stale activity.
    if (!enabled) this.memory.activity.clear();
  }

  drainMemoryActivity(recycle?: Uint8Array | null): Uint8Array | null {
    if (!this.memory.activity.enabled) return null;
    return this.memory.activity.drain(recycle);
  }

  keyEvent(e: KeyboardEvent, down: boolean): boolean {
    return this.keyboard.handleKey(e, down);
  }

  setKey(token: string, down: boolean): void {
    this.keyboard.setKey(token, down);
  }

  releaseAllKeys(): void {
    this.keyboard.releaseAll();
  }

  dispose(): void {
    if (this.disposed) return;
    this.disposed = true;
    this.keyboard.releaseAll();
    // Drop the frame buffer and any queued load so they are freed at once
    // rather than waiting on GC of the whole machine.
    this.imageData = null;
    this.pendingImage = null;
    this.runLatch.clear();
  }
}
