import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { dialects } from '../src/dialects/registry';
import {
  GLYPH_SOURCES,
  formatAddress,
  glyphLocation,
  type GlyphSource,
} from '../src/dialects/glyphSources';

/**
 * Regenerate the address index in docs/contributing/glyph-sources.md from
 * src/dialects/glyphSources.ts. Everything between the markers belongs to this
 * script; the prose around them is hand-written and left alone.
 *
 * The declaration is base + stride + index rule; this materialises it to one
 * line per character code, which is what makes an address greppable. Both
 * halves matter: the declaration is what a human maintains, the index is what a
 * search finds. glyph-sources.test.ts regenerates and diffs, so a stale
 * committed copy fails the suite.
 */

const here = dirname(fileURLToPath(import.meta.url));
const docPath = resolve(here, '../docs/contributing/glyph-sources.md');

const BEGIN = '<!-- glyphsources:begin -->';
const END = '<!-- glyphsources:end -->';

const hex = (n: number, width = 2): string =>
  `0x${n.toString(16).toUpperCase().padStart(width, '0')}`;

/** Collapse a sorted code list into `0x80-0x8F, 0xA0` style ranges. */
function ranges(codes: number[]): string {
  if (codes.length === 0) return '—';
  const sorted = [...codes].sort((a, b) => a - b);
  const out: string[] = [];
  let start = sorted[0]!;
  let prev = start;
  for (const code of sorted.slice(1)) {
    if (code === prev + 1) {
      prev = code;
      continue;
    }
    out.push(start === prev ? hex(start) : `${hex(start)}-${hex(prev)}`);
    start = code;
    prev = code;
  }
  out.push(start === prev ? hex(start) : `${hex(start)}-${hex(prev)}`);
  return out.join(', ');
}

/** Codes this source actually accounts for (an index rule may skip some). */
function claimed(source: GlyphSource): number[] {
  if (source.kind === 'logic') return source.codes;
  return source.codes.filter((c) => source.indexOf(c) !== undefined);
}

function whereColumn(dialectId: string, source: GlyphSource): string {
  if (source.kind === 'logic') return `generated by ${source.by}`;
  if (source.kind === 'chip') return `${source.chip} internal ROM`;
  if (source.base < 0)
    return `\`${source.file}\` (machine address not established)`;
  // The base alone is ambiguous - it is only useful with the code it names and
  // the step between codes, which is exactly the offset kept out of it.
  return (
    `\`${source.file}\` @ ${formatAddress(dialectId, source.base)}` +
    ` = ${source.baseCodeIs ?? 'code'} ${hex(source.baseCode)}, +${source.stride}/code`
  );
}

function summary(): string {
  const rows = [
    '| Machine | Codes | Where the shape lives | Cell |',
    '| --- | --- | --- | --- |',
  ];
  for (const dialect of dialects) {
    for (const source of GLYPH_SOURCES[dialect.id] ?? []) {
      const codes = claimed(source);
      if (codes.length === 0) continue;
      rows.push(
        `| ${dialect.name} | ${ranges(codes)} | ${whereColumn(dialect.id, source)} | ${source.cell.w}×${source.cell.h} |`,
      );
    }
  }
  return rows.join('\n');
}

/** One line per code, so an address can be found by searching for it. */
function index(): string {
  const out: string[] = [];
  for (const dialect of dialects) {
    const lines: string[] = [];
    for (let code = 0; code <= 0xff; code++) {
      const loc = glyphLocation(dialect.id, code);
      if (!loc) continue;
      if (loc.kind === 'rom') {
        const addr =
          loc.address < 0
            ? '        —'
            : formatAddress(dialect.id, loc.address).padStart(9);
        lines.push(
          `${hex(code)}  ${addr}  ${loc.file} @ ${hex(loc.fileOffset, 4)}`,
        );
      } else if (loc.kind === 'chip') {
        lines.push(
          `${hex(code)}  ${`${loc.chip}`.padStart(9)}  glyph ${hex(loc.index)}`,
        );
      } else {
        lines.push(`${hex(code)}  ${'—'.padStart(9)}  generated by ${loc.by}`);
      }
    }
    if (lines.length === 0) continue;
    out.push(
      `### ${dialect.name}`,
      '',
      '```text',
      // The code is this machine's character code and the address is in its own
      // notation; the file offset is an offset into an image this repo ships,
      // which is a different kind of thing, so it stays 0x.
      'code    address  image file @ 0x offset',
      ...lines,
      '```',
      '',
    );
  }
  return out.join('\n');
}

const generated = [
  BEGIN,
  '',
  '<!-- Generated by scripts/gen-glyph-addresses.mts. Do not edit by hand:',
  '     run `npm run gen:glyphs`. Prose outside the markers is kept. -->',
  '',
  '## Where each machine keeps its glyphs',
  '',
  summary(),
  '',
  'The address column is the number **the machine itself documents**, written the',
  'way that machine writes one - `&C000` on the Acorns and Amstrads, `$D000` on',
  'the Commodores, `#8000` on the Atom - followed by the code it names and the',
  'step between codes. Those two are stated rather than folded into the address,',
  "because they differ per machine: the Spectrum's CHARS names code 0 while its",
  "table starts at 0x20, and the BBC's &C000 names 0x20 directly.",
  '',
  'Where the column reads "generated", nothing is stored anywhere - the shape',
  "comes out of the code's own bits - so there is no address to record and none",
  'is invented.',
  '',
  '## Address index',
  '',
  'One line per character code, so an address can be found by searching for it.',
  'Addresses are hex even for the machines whose manuals count in decimal;',
  "translating a decimal input is the searching side's job.",
  '',
  index().trimEnd(),
  '',
  END,
].join('\n');

const doc = readFileSync(docPath, 'utf8');
const start = doc.indexOf(BEGIN);
const stop = doc.indexOf(END);
if (start === -1 || stop === -1) {
  throw new Error(`${docPath} is missing the ${BEGIN} / ${END} markers`);
}
writeFileSync(
  docPath,
  doc.slice(0, start) + generated + doc.slice(stop + END.length),
  'utf8',
);
console.log(`wrote docs/contributing/glyph-sources.md`);
